### ISSUE TITLE
The dimensionless unit of yt fields

### ISSUE THREAD

**Issue by KISSFORMISS** [AMReX-Astro/Castro#100]
If I read the plot files via yt and print the fields like 'rho_o16' or 'omegadot_o16', it shows they are dimensionless. But for 'Temp' or 'density', they have correct unit.

**Comment by zingale** [comment]
you'll have to add these yourself.  Look in yt in `yt/frontends/boxlib/fields.py` 

You'll want to define the fields to be known to yt with appropriate units and then issue a PR to the yt bitbucket repo.

**Comment by maxpkatz** [comment]
I think that directly writing the fields into the yt frontend is suboptimal. This means that we'll have to issue a new PR to yt every time there is a units-affecting change in our plotfiles. This could be for many reasons, like we add new default derived fields, or we change the name of existing derived fields, or a user defines their own derived field that we don't control.

I propose instead that we add a units file to the plotfile directory that writes out the units (in some syntax that we'll specify in advance) in the same order that the fields appear in the plotfile, and have the yt frontend read those in. Then all we need to do is require that any field added to Castro state data has an associated units data vector that will be written to this file when a plotfile call is issued.

**Comment by zingale** [comment]
this issue is quite old, and we seem to be doing okay with yt, so closing this for now
