### ISSUE TITLE
consider setting small_pres automatically

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1000]
Currently, if small_pres is not set, we default to 1.e-200, which is quite small.  We should try to find a robust way to set it via the EOS.

**Comment by maxpkatz** [comment]
The main challenge here I have faced when I thought about doing this is that small_pres = small_pres(small_dens, small_temp, X); what should we choose for X? Do we need to grid search over all possible combinations of X to find small_pres?
