### ISSUE TITLE
SDC-4 is not threadsafe

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1030]
When you run a problem with SDC-4 (like `hse_convergence` using the `inputs.sdc4-reflect.testsuite`) using OpenMP, there are a lot of density reset errors right at the start and then it crashes.  We are probably tiling a loop that should not be tiled somewhere.

**Comment by mattrjackson** [comment]
Just a note, I've been learning CASTRO and recently tested  the OpenMP-only compile (without MPI) and have found odd crashes (CFL convergence failures) on a pure hydro calculation, that don't occur for a pure MPI build. Unfortunately can't share the full test case, but I suspect it also falls along the lines of what you mention.

**Comment by zingale** [comment]
as best as I can tell, this is only an issue with the 4th order solver.  We test nightly with openmp for a large number of problems and don't see any crashes, so if you could send us something reproducible, I'd appreciate it so we can track it down.
