### ISSUE TITLE
hardcoded state indices in Derive_nd.f90

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#106]
The various velocity derived variable routines (like `ca_dermagvort` and `ca_derdivu` hardcode `2`, `3`, and `4` in for the momentum components instead of using `UMX`, `UMY`, and `UMZ`

**Comment by maxpkatz** [comment]
I do not consider this an issue. In general there is not a correlation between the components handed to derive routines and the indexing present in state data. This particular case matches the state data indexing but I do not want to start mixing and matching in the derive routines.

**Comment by maxpkatz** [comment]
Closing. Not a bug.
