### ISSUE TITLE
Minor error in potential calculation in gravity sources

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#109]
Source/Src_nd/gravity_sources_nd.F90 creates a time-centered potential array out of the old and new potentials for the purpose of calculating the gravitational source term. In doing so, it deals with the fact that Poisson gravity solver sets the ghost zone boundary value for the potential at outflow boundaries at cell edges, not at cell centers, by extrapolating to what the value would be at the cell edge. However, this calculation is incorrect for symmetry boundaries; on symmetry boundaries, the potential value in the ghost zone is the actual ghost zone cell center, and not located at the domain boundary. Hence for symmetry boundaries, we simply should accept the value that is already in the ghost zone.

This had no effect on the accuracy of calculations because the hydrodynamic flux is automatically zero at a symmetry boundary, so it did not matter what the value of the potential was.

Another minor issue is that corner ghost zones (i.e. (i,j,k) == (-1,-1,-1)) do not have meaningful data values and indeed may have NaNs, so we should skip those corners when doing the ghost zone calculation. Again, this had no impact on the simulation because the corners are not used in the gravitational energy update.

**Comment by zingale** [comment]
is this the same corner ghost cell issue that I was complaining about elsewhere?
