### ISSUE TITLE
Out of bounds access in gravity interpolation

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#1118]
The functionality that interpolates gravity from coarse levels to fine levels (gravity.max_solve_level) has an out-of-bounds access to the coarse grad phi data. Reproducer is wdmerger, built with

```
$ make COMP=gnu USE_MPI=FALSE DIM=2 DEBUG=TRUE
```

and run with

```
./Castro2d.gnu.DEBUG.ex inputs-repro
```

where `inputs-repro` is attached. The reported error within `InterpFromCoarseLevel` (called from within the `multilevel_solve_for_new_phi` at initialization) is:

```
amrex::Abort::0:: (0,53,0,0) is out of bound (0:9,11:52,0:0,0:0) !!!
```

and the backtrace points to

```
 6: ./Castro2d.gnu.DEBUG.ex() [0x10044418]
    amrex::Array4<double const>::index_assert(int, int, int, int) const
/ccs/home/maxpkatz/summit/codes/amrex/Src/Base/AMReX_Array4.H:185

 7: ./Castro2d.gnu.DEBUG.ex() [0x1041edac]
    double const& amrex::Array4<double const>::operator()<double const, 0>(int, int, int, int) const inlined at /ccs/home/maxpkatz/summit/codes/amrex/Src/AmrCore/AMReX_Interp_2D_C.H:393 in amrex::NodeBilinear::interp(a
mrex::FArrayBox const&, int, amrex::FArrayBox&, int, int, amrex::Box const&, amrex::IntVect const&, amrex::Geometry const&, amrex::Geometry const&, amrex::Vector<amrex::BCRec, std::allocator<amrex::BCRec> > const&, int
, int, amrex::RunOn)
/ccs/home/maxpkatz/summit/codes/amrex/Src/Base/AMReX_Array4.H:77
void amrex::nodebilin_slopes<double>(amrex::Box const&, amrex::Array4<double> const&, amrex::Array4<double const> const&, int, int, amrex::IntVect const&)
/ccs/home/maxpkatz/summit/codes/amrex/Src/AmrCore/AMReX_Interp_2D_C.H:393
amrex::NodeBilinear::interp(amrex::FArrayBox const&, int, amrex::FArrayBox&, int, int, amrex::Box const&, amrex::IntVect const&, amrex::Geometry const&, amrex::Geometry const&, amrex::Vector<amrex::BCRec, std::allocato
r<amrex::BCRec> > const&, int, int, amrex::RunOn)
/ccs/home/maxpkatz/summit/codes/amrex/Src/AmrCore/AMReX_Interpolater.cpp:133
```
[inputs-repro.txt](https://github.com/AMReX-Astro/Castro/files/4888892/inputs-repro.txt)
[probin-repro.txt](https://github.com/AMReX-Astro/Castro/files/4888893/probin-repro.txt)

**Comment by WeiqunZhang** [comment]
I think this is the long-standing issue that we don't have a interpolater for face data. I can write a simple one quickly.  That should at least be better than the current situation.

**Comment by maxpkatz** [comment]
Ah yes, that's what you were reporting in #469. This makes a lot more sense now.

**Comment by WeiqunZhang** [comment]
When I try to run, I get this.  What did I do wrong?

```$ ./Castro2d.gnu.ex inputs-repro 
AMReX (20.07-32-ge79dab47730c) initialized

Starting run at 22:29:45 UTC on 2020-07-08.
Successfully read inputs file ... 

Castro git describe: 20.07-28-g9d189eb
AMReX git describe: 20.07-32-ge79dab4
Microphysics git describe: 20.07-9-gcfae851

reading extern runtime parameters ...
amrex::Error::0::ERROR: problem in the extern namelist !!!
SIGABRT
```

**Comment by WeiqunZhang** [comment]
Sorry, I cannot get Castro to run.  Could you try https://github.com/AMReX-Codes/amrex/pull/1118?  You need to use `face_linear_interp` instead of `node_linear_interp`.  Please also teach me how to run Castro.  Maybe I need to a fresh clone?  I might have some old files hanging around.  That used to cause problems sometimes.

**Comment by maxpkatz** [comment]
It looks like that PR does what I'm looking for, thanks.

Regarding building Castro -- the two things that come to mind are (1) you need to have the latest development branch of Microphysics and (2) make sure there aren't any temporary build files lying around. In previous versions of Castro we'd put some temporary files like extern.F90, prob_params_auto.F90, extern_parameters.H, and actual_network.F90 in your build directory. Now we put them all in tmp_build_dir, but if you have some old files lying around (check for any files that aren't tracked by git, or look at the ones we explicitly remove in the `clean` target at the end of Make.Castro) you'll need to delete them.
