### ISSUE TITLE
MLMG V-cycles dominated by communication costs for small problems on Summit

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#1126]
For a 4-node run on Summit of a 2D wdmerger collision problem, where the base grid is 512x1024 and the fine grid jumps by a factor of 4, the MLMG time is almost entirely dominated by calls to ParallelCopy in MLMG:addInterpCorrection(). This setup has 32 128x128 grids on the coarse level and 26 128x128 grids on the fine level (spread over 24 ranks). Due to the small amount of computation it is not surprising that communication plays a large role but the quantitative effect is surprising: a typical V-cycle in the fine level gravity solve runs for 100-200 ms and 95-99% of that is typically spent in this ParallelCopy call.

**Comment by maxpkatz** [comment]
I misunderstood the problem. 22 of the 24 ranks are spending this 100-200 milliseconds in MPI_Waitall. The other two ranks (rank 0 and rank 1) are spending all this time in the bottom solver. (These are presumably the two ranks that have two grids instead of 1, since I have 26 grids over 24 ranks.) The bottom solve on these ranks (bicgstab) is taking a disproportionately long time compared to the up and down parts of the V cycle (e.g. 150 ms compared to 5 ms).

**Comment by jmsexton03** [comment]
Have you played around with the default agglomeration settings for mlmg? Nyx initially had that set to off, and there are some thresholds you can set. Not sure it would help the problem size you mentioned though, or if it's not a communication issue

**Comment by maxpkatz** [comment]
This should be reproducible by compiling Castro wdmerger with
```
make -j DIM=2 TINY_PROFILE=TRUE COMP=PGI USE_MPI=TRUE USE_CUDA=TRUE
```
and running on Summit (using four nodes) with
```
jsrun -n 24 -r 6 -c 1 -a 1 -g 1 -X 1 -brs Castro2d.pgi.TPROF.MPI.CUDA.ex inputs
```
Inputs and probin file are attached.
[inputs.txt](https://github.com/AMReX-Astro/Castro/files/4905821/inputs.txt)
[probin.txt](https://github.com/AMReX-Astro/Castro/files/4905823/probin.txt)

**Comment by WeiqunZhang** [comment]
I have a branch in my amrex fork that has improved the performance.  The bottom solver time goes down from 11.0 to 5.2, and the coarse time step does from 16.5 to 9.7.  I will do a pull-request to amrex, after some cleanups and https://github.com/AMReX-Codes/amrex/pull/1135 is merged.
