### ISSUE TITLE
PhiRot_Type and Rotation_Type should be removed

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#1127]
The rotational phi and acceleration state types were originally added for two reasons: (1) it was useful to have a stateful version of the acceleration in the scenario where the rotation period is changing with time; (2) the energy update for rot_source_type == 4 was written based on the rotational "potential" to be symmetric with gravity. (1) is no longer an issue because we removed the ability for omega to change in time, and we don't plan to bring it back. (2) is not required; we can recast the conservative energy update entirely in terms of the acceleration, as we have done for gravity. So we should remove these StateData types to save on memory.

**Comment by zingale** [comment]
I think we are clear to do this now

**Comment by maxpkatz** [comment]
Rotation_Type has already been removed. PhiRot_Type (which is just a scalar) still exists, and will have to be removed from a couple places for this to occur. The first is in the SCF code, the second is in wdmerger's derived quantities.

**Comment by zingale** [comment]
to remove it in the derived quantities, should we just recompute it locally as needed?

**Comment by maxpkatz** [comment]
Yes, that could be done.

**Comment by zingale** [comment]
this is implemented in #1974
