### ISSUE TITLE
JOSS: repo size

### ISSUE THREAD

**Issue by bonh** [AMReX-Astro/Castro#1154]
https://github.com/openjournals/joss-reviews/issues/2513

The directory `.git` has around 100 MB which is huge compared to the total size of the repo being around 130 MB, right? Perhaps there is some easy and convenient way to clean up the `.git` folder somehow? `git gc`?

**Comment by zingale** [comment]
running `git gc` doesn't really change these sizes.  The history goes back 10 years, so I don't think that these relative sizes are a big issue, as the code has undergone a lot of changes in that decade.

**Comment by bonh** [comment]
Okay, I get this, thank you. But if you run `git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| sed -n 's/^blob //p' \
| sort --numeric-sort --key=2 \
| cut -c 1-12,41- \
| $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest`, which is the second answer from here [https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history](), you will notice that there are a bunch of larger blobs containing data or binaries, most likely pretty old (haven't checked). I assume, that you could remove the old data from the history and reduce the size of your repo significantly.

Note, that in my opinion this issue does not prevent acceptance by JOSS. So if you really do not think it is worth the effort feel free to close this issue.

**Comment by zingale** [comment]
I'll take a look.

Part of the issue is that we report the git hashes of the code used in the science papers we write, so we really don't want to change the history.  And some of those older files are older initial models that have since been replaced, but if we want to go back to a science paper from a few years ago, we may need some of those.

**Comment by bonh** [comment]
Excellent reasons to keep the history!
