### ISSUE TITLE
time_integration_method runtime parameter is redundant

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1167]
Since we need to compile in support for the different time integration methods, we really don't need time_integration_method as a runtime parameter.  Instead we can set it as:
```
time_integration_method = 0;
#ifdef SIMPLIFIED_SDC
time_integration_method = 3;
#endif  
#ifdef TRUE_SDC
time_integration_method = 2;
#endif  
```

**Comment by maxpkatz** [comment]
I don't disagree, but I would like it ultimately to be true that you can switch between Strang and simplified SDC in the same binary. Perhaps when we get there we can use a different runtime parameter for that.

**Comment by zingale** [comment]
closing this for now -- we have no plans to change this currently.
