### ISSUE TITLE
SDC sources simplification

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#117]
in computing the reaction source term seen by hydro, we need it expressed in terms of primitive variables.    Instead of doing the conversion that we do in terms of the preliminary conservative state, converted to a primitive state, can't we just run `srctoprim()` on the conservative approximation to this change (Eq. 27 in the notes)

@drummerdoc @maxpkatz

**Comment by zingale** [comment]
Looking more at this, we can compute 

I_U = (U^{n+1} - U^n)/dt - A(U)^{n+1/2}

directly from the update.  And we want

I_q = (q^{n+1} - q^n)/dt - A(q)^{n+1/2}

The problem is that I_U has units of variable / time, and since calling ctoprim on this requires an actual thermodynamic state (since we call the EOS), it is not clear that we can just through I_U through the EOS machinery.

That is why we do the more long-winded approach of contructing A(q) in the code.

So, unless I am missing something, the EOS makes this unpossible.

**Comment by zingale** [comment]
in particlar, we need dp/de |_rho if there is an source to internal energy.  I think there won't be unless we have explicit diffusion, or external heating.  Maybe we are safe in some cases then?

**Comment by drummerdoc** [comment]
Sorry, can you explain how the more "long-winded" formation of A(q) in the code actually gets around requiring dp/de |_rho when using srctoprim?  In Pele I have explicit diffusion and/or heating terms.  When I went through this, I must have missed something, because I couldn't see a reason to keep that long-winded routine.  Thanks.

**Comment by zingale** [comment]
We create the state variables themselves (temporarily), instead of just the update.  Then we can call the EOS as needed, because the EOS can work on the state variables.  This allows us to convert to the primitive state, and construct that term.

If we just have the update, since the EOS is non-linear in rho and e, the EOS called on the update will not be well-defined.

**Comment by drummerdoc** [comment]
Ahh, yes.  I need to go back and look more closely.  Thanks!
