### ISSUE TITLE
port initial model parser to C++

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1245]
Many of the problem setups rely on the initial model parser to managed reading and initial model and then mapping it onto the domain.  Many problem derives also use the model parser (e.g. reacting_bubble), so when we convert a problem over to the C++ parser, we also need to convert the derives.

Finally, there is one general source file that uses the model parser: bc_ext_fill_nd.F90 -- in this case, we should use a C++ version of this routine if we are doing a C++ model read (which means we've already defined `GPU_COMPATIBLE_PROBLEM = TRUE`

**Comment by maxpkatz** [comment]
GPU_COMPATIBLE_PROBLEM is actually not required for the C++ initialization, as an aside.

**Comment by zingale** [comment]
and the interpolation in bc_ext_fill_nd is only used in ext_denfill -- not sure if this is really used.

**Comment by zingale** [comment]
this is done in #1247
