### ISSUE TITLE
limit_hydro_fluxes_on_small_dens gives different results based on number of MPI ranks

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#132]
For wdmerger, results are identical to roundoff when not using it, but can vary at a much larger level when the flux limiter is on. This appears to be due to some inconsistency on box edges.

**Comment by zingale** [comment]
it also appears that area factors are needed in the LF flux construction

**Comment by zingale** [comment]
from @maxpkatz pkatz, the following triggers this:
```
    do k = lo(3), hi(3)
       do j = lo(2), hi(2) + 1
          do i = lo(1), hi(1)

             if (u(i,j,k,UEINT) < 1.0d15 .or. u(i,j-1,k,UEINT) < 1.0d15) then

                flux2(i,j,k,:) = ZERO

             endif

          enddo
       enddo
    enddo
```

**Comment by zingale** [comment]
is this still an issue with the new version of the limiting ?
@mkatz?

**Comment by maxpkatz** [comment]
As far as I can tell, removing the limiting based on internal energy resolves the issue I observed (this is in version 17.08). I do not know why it fixes the issue.
