### ISSUE TITLE
port StarLord changes into Castro

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#136]
We should start refactoring the interfaces in Castro to align with the changes made to StarLord to allow for the GPU offloading.

Changes include:
  * ~~making interfaces take `lo()` and `hi()`, instead of `lo1, lo2, ...`~~
  * making `initdata` use `bind(C)`
  * make the interfaces `_nd` instead of `_1d`, `_2d`, and `_3d`.  
  * pass in `q` entirely, instead of slicing it with `QPRES`, `QU`, ... (e.g., for `uflaten`)

**Comment by maxpkatz** [comment]
Some big changes that still need to happen:

Merge Castro_{advection,mol}_{1,2,3}d.F90
Merge riemann_{1,2,3}d.F90?
Do not pass sliced q arrays into ppm_reconstruct
Move array allocations (i.e. bl_allocate) out of the Fortran and into the C++

**Comment by maxpkatz** [comment]
All hydro routines that operate over a region should operate over a box that is passed in to the routine. They should not do something like accept (lo, hi) from the tilebox and then proceed to loop over (lo-3, hi+3). If that is needed, pass in two additional arrays giving the bounds of the actual box to compute over, even if this means doing some unneeded calculations on the box corners or edges.

**Comment by maxpkatz** [comment]
Related: #214

**Comment by zingale** [comment]
I think we have separate issues for all the remaining stuff here (maybe not for "move array allocations out of Fortran) -- okay to close and create a new issue for this one task?

**Comment by maxpkatz** [comment]
Sure, I'll close it. There may be more changes required but we can use specific issues for those.
