### ISSUE TITLE
Riemann solver HLLC doesn't support HYBRID_MOMENTUM

### ISSUE THREAD

**Issue by guadabsb15** [AMReX-Astro/Castro#140]
When using option castro.riemann_solver = 2 in the wdmerger problem,   I get  "amrex::Abort::1::State has NaNs in the rmom component::check_for_nan() !!! " after the first hydro advance

**Comment by maxpkatz** [comment]
The reason I did not implement support for HLLC is that I construct the hybrid momentum flux by using the edge values of the linear momentum obtained from the Riemann solver in constructing edge values of the angular momentum. HLLC does not directly give edge values of the state, only the fluxes.

**Comment by zingale** [comment]
I wonder if we could formulate HLLC in terms of angular momentum?

If it is not obvious, then we should atleast abort with a nice message if we try running with hybrid

**Comment by maxpkatz** [comment]
Yes, there may be a way to do that. I wonder if there may also be a way to express the angular momentum fluxes in terms of the linear momentum fluxes directly.

If we cannot come up with a solution to this quickly, I will implement that abort message.

**Comment by maxpkatz** [comment]
Abort message implemented. Closing as wontfix.

**Comment by maxpkatz** [comment]
Does MHD require an HLL type solver?
