### ISSUE TITLE
add RHD blast wave from paper II

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1525]
I got an email request for the blast wave problem from paper II (Castro gray radiation).  Weiqun sent the attached old problem setup.  We should update it for the current code.
[RHD_blast.tar.gz](https://github.com/AMReX-Astro/Castro/files/5791455/RHD_blast.tar.gz)

**Comment by maxpkatz** [comment]
I've written this test up in #1555. I've done some smoke testing to verify that 1D/2D/3D all work, and that the blast wave is approximately in the right place and with the right density at the end of the simulation time (10^6 s). I did not do a detailed analysis, but the user is welcome to let us know if something does not look right.
