### ISSUE TITLE
SDC + NSE fails for massive star

### ISSUE THREAD

**Issue by harpolea** [AMReX-Astro/Castro#1571]
When running the `rotating_star` problem with NSE and simplified SDC, the problem crashes during the first timestep after attempting several retries. The timestep it tries is a couple of orders of magnitude larger than that used in a successful Strang + NSE run (~1e-5 vs ~1e-7), so it may be that it's being too ambitious with this at the start.

**Comment by zingale** [comment]
update: I no longer see different timesteps between Strang and simplfiied-SDC

But I do see simplified-SDC failing the VODE burn in the first step.  This goes away if we drop `rho_nse` down to `2.e6`, which is reasonable as long as the Si constraint is in place.

I think that the SDC solve is just having more trouble, and aprox19 is a tough network.  We could also try loosening the tolerances (especially atol_spec) and trying the numerical Jacobian.

**Comment by zingale** [comment]
this is fixed by the recently merged PR: https://github.com/starkiller-astro/Microphysics/pull/643

@harpolea can you confirm?

**Comment by harpolea** [comment]
Yes, I just tried running this and SDC+NSE gets past at least the first couple of time steps, so it looks like this bug is now fixed.
