### ISSUE TITLE
new directory structure

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#158]
It's time to further separate code into directories by topic.  This will make it easier to merge the Nyx MHD into Castro.

Some thoughts:

  * we should no longer have separate `Src_1d`, `Src_2d`, `Src_3d`, and `Src_nd` directories.  Since we are removing much of the dimensional dependence from the code, this sort of distinction will soon not be necessary

Organization proposal:

  * `Castro/Source/`
    * `diffusion/`
    * `driver/`
    * `gravity/`
    * `hydro/`
    * `mhd/`
    * `radiation/`
    * `reactions/`
    * `source_terms/`

**Comment by zingale** [comment]
@WeiqunZhang @asalmgren please share any thoughts you might have on this.

**Comment by asalmgren** [comment]
I agree with splitting out the files into directories.  I think it's helpful in Nyx although there's still too much in the Src directory itself.

**Comment by zingale** [comment]
this has been merged
