### ISSUE TITLE
Sedov problem needs cleanup

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#160]
The Sedov problem setup should be cleaned up. Issues:

- ~~There is an option to set the ambient temperature instead of ambient pressure, but that only exists in the 2D version.~~
- The BC fill routine doesn't make much sense, it sets the physical ghost zones to a strange amalgamation of the inner ghost zone and the ambient material.
- It's also not clear that we even need to worry about a special ghost zone fill in this problem.
- ~~The probtype values as integers are not especially clear, and Prob_3d.f90 lacks comments on the difference between the two options.~~

For problem setups that are somewhat complicated and have multiple options, it makes sense to switch them to the dimension agnostic version of the problem setup to avoid conflicts between the versions. This could be considered here.

**Comment by maxpkatz** [comment]
Since the probtype values only deal with the geometry of the problem, I don't think we need to have them at all. We can detect what the geometry obtained from the inputs file is, and set the correct problem type appropriately.

**Comment by zingale** [comment]
I think that we should get rid of the bc_fill for this setup.

I agree with the geometry stuff

**Comment by zingale** [comment]
this has all be fixed.

**Comment by maxpkatz** [comment]
What about the dimension agnostification?
