### ISSUE TITLE
explore getting rid of hydro_source

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1631]
We use the `hydro_source` MF to store the update from hydro, essentially -div{F(U)}.  But do we really need a separate MF for this?  It looks like we can eliminate it for Strang without too much difficulty.  We should see whether this is true for simplified-SDC.

**Comment by zingale** [comment]
I think we can accomplish this in a straightforward fashion if we get rid of the "apply_sources_consecutively` option.

In that case, we simply have `do_old_sources` add the sources to the `Source_Type` old time StateData and _not_ apply it to S_new just yet.  Then we call `construct_ctu_hydro_source`, and have that apply the hydro source to the `Source_Type` old time StateData as well.

After that, we apply the `Source_Type` old time to `S_new`, and we wind up with the same result at that point:

U^{n+1} = U^n + dt * (-div{F} + S^n)

the rest remains unchanged for Strang.  For simplified-SDC, we would just then add the old and new time `Source_Type` to get the hydro source for the burn.

**Comment by zingale** [comment]
there is only one problem that is currently using `apply_sources_consecutively`

**Comment by maxpkatz** [comment]
I have no interest in retaining `apply_sources_consecutively`. When I did the source term refactor, `apply_sources_consecutively` was there to retain the legacy behavior, and I think its presence in a test problem at this point is just for test suite coverage.

**Comment by maxpkatz** [comment]
This tentatively looks OK to me. The one difficulty I identify now is that it makes it harder to do `print_update_diagnostics()` on just the hydro state. If we want to keep that functionality, we could save the diagnostic values from the old source and then subtract it after we calculate the diagnostic after the hydro.

**Comment by zingale** [comment]
with #1636, we can now implement this

**Comment by zingale** [comment]
oh, there is a fundamental issue here: Source_Type only has NSRC components, while hydro_source has NUM_STATE components.  They are only the same if we are running with PRIM_SPECIES_HAVE_SOURCES

**Comment by zingale** [comment]
the alternative is to add the hydro update directly to S_new for Strang and simplified-SDC, and then when computing sum_of_sources for simplified-SDC, so:

S_new - Sborder + Source_new

**Comment by maxpkatz** [comment]
I like that one better. Modifying the Source_Type data makes me nervous because that data is used for time interpolations on fine level regridding operations.

**Comment by zingale** [comment]
Actually, I think the above is wrong.  At the time we need to compute sum_of_sources, S_new already had the source correction, so it is:

U^n + dt A + (dt/2) (S^n + S^{n+1/2})

so we just need to subtract Sborder and divide by dt.

**Comment by zingale** [comment]
Here's the additional complication.  After we burn, we need to compute the reactive source for the next iteration's hydro prediction (this is done in `get_react_source_prim`).  To do this, we need to know what A  + 1/2 (S^n + S^{n+1}) was.  But now we can't get that from S_new, because we just updated S_new with reactions.  

What we could try to do is stash the advection + source terms into `Simplified_SDC_React_Type` before the burn, and then pull from there in `get_react_source_prim` before overwriting it.  But the issue there is that we rely on having last iteration's source stored there not only for the hydro prediction, but for NSE, to do the predictor-corrector NSE update in the burn.  

This would mean that we would have to put the stashing of advection + source terms into `Simplified_SDC_React_Type` right in the inner loop just before we burn.  This will work (and we actually have that data already computed there), but we usually do this sort of thing on the Box or MF level, not on the zone-by-zone level.
