### ISSUE TITLE
consolidate the source MFs into a single one

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#165]
We currently have separate MFs for each of the physics component's contributions to the source.  We should replace this with only a single MF for the source term for all physics.

Need to ensure if we can still do the Coriolis implicitly in this framework.

**Comment by maxpkatz** [comment]
The wdmerger relaxation currently depends on being able to pick out the gravitational source (it needs this to be able to balance the gravity + hydro sources against the rotation force).
