### ISSUE TITLE
merge the self-consistent field initialization into mainline Castro

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#169]
A while back there was an implementation of the self-consistent field (SCF) initialization for binary white dwarfs in the `wdmerger` repo, in `prob.cpp`.   This should be recovered from the git history and then merged into Castro proper.  

This capability will also be useful for single rapidly-rotating stars.

**Comment by maxpkatz** [comment]
This existed at least as recently as December 2015, for example in wdmerger commit 742121c98699f08a423776a591ef8006fe646051.

**Comment by maxpkatz** [comment]
For wdmerger I implemented this for a binary system, but we'll want to have the capability to switch easily between single and binary systems.

**Comment by maxpkatz** [comment]
This is currently a WIP on the scf_relaxation branch.

**Comment by harpolea** [comment]
Fixed in #530
