### ISSUE TITLE
eliminate sources_for_hydro

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1706]
We can eliminate the MF `sources_for_hydro` if we just have the `srctoprim` routine add `source_corrector` to the old-time `Source_Type` before converting to primitive.

**Comment by maxpkatz** [comment]
I would be OK with this as long as we are only modifying the local temporary variable and not Source_Type itself. I think it is correct.

**Comment by zingale** [comment]
yes, that is the idea

**Comment by zingale** [comment]
this was finished in #1711
