### ISSUE TITLE
set_method_params is slow when using many processors

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#172]
When using at least 16-32 MPI ranks, the call to set_method_params can take over 100 seconds when using GNU. This is reproduced on multiple systems. It takes much less when using Cray.

**Comment by zingale** [comment]
any OpenMP? or this is pure MPI?

**Comment by maxpkatz** [comment]
I've been building with OpenMP but using only one thread per rank.

**Comment by maxpkatz** [comment]
The slowness comes from multiple processors trying to read the Helmholtz table at the same time.

**Comment by maxpkatz** [comment]
A solution to this is proposed in Microphysics PR #53, which broadcasts the table rather than having all processors read it.

**Comment by zingale** [comment]
this should be fixed with the latest AMReX and Microphysics
