### ISSUE TITLE
Timestep retry scheme is not conservative

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#178]
I observe a wdmerger collision case where the retry scheme is significantly non-conservative (reverses the sign of the energy on the grid in one step). I have a reproducer for this case and when I only allow the retry scheme to use a single subcycle (effectively disabling it, but still using the machinery), the scheme is still non-conservative, so there must be a fundamental issue.

**Comment by maxpkatz** [comment]
The StateData swapping scheme prior to beginning the subcycling is incorrect. We should not do an additional swap of the old and new data before the subcycling starts, because the StateData was copied after the swap had been already done at the beginning of the timestep. So the "old" data actually has the n+1 state, and vice versa. So we just want a single swap.

**Comment by maxpkatz** [comment]
I suspect that this is related to gravity, because the non-conservation I witnesses is in the total energy; the other quantities (e.g. mass) don't appear to have sudden jumps like the total energy does. So we may be handling the gravitational potential incorrectly during a retry.

**Comment by maxpkatz** [comment]
The swapping of the gravity time levels might be incorrect, this should be examined at some point. But it has no practical effect, I think, since we always recompute the old and new time gravity anyway.

**Comment by maxpkatz** [comment]
The issue is in the fluxes. These are intentionally added over all subcycles in the saved fluxes MultiFab -- this way the fluxes at the end of the subcycled timestep are the fluxes for a full timestep, so that if we have multiple levels, the fluxes make sense when doing the reflux. But, the gravity source term uses the fluxes and expects it to just have the fluxes in that timestep. So there is an inconsistency that needs to be resolved.

**Comment by zingale** [comment]
instead of storing the fluxes (3 dirs X NVAR), what if we just create a MF that evaluates the source in `consup` from the current fluxes and passes that out?  Then in the source stuff we can use it?  This would use a lot less memory.

**Comment by maxpkatz** [comment]
That won't work because the source is flux * phi, and we don't have the new-time potential until after the hydro has completed.

**Comment by maxpkatz** [comment]
What I could do to lower the memory footprint is only store the density flux.

**Comment by zingale** [comment]
yeah, that's good.
