### ISSUE TITLE
Rename Network_dir to NETWORK_DIR, EOS_dir to EOS_DIR

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#182]
This is an inconsistency between Castro and Maestro/Microphysics that makes it annoying to go back and forth between them.

For legacy purposes we should still allow the old options in Castro, but have them be copied to the all-caps variable names.

**Comment by zingale** [comment]
agreed.  Good hackathon issue

**Comment by zingale** [comment]
for posterity, these were the commands to change things

```
for i in `ack -l Network_dir`; do sed -i -e 's/Network_dir/NETWORK_DIR/g' $i; done
for i in `ack -l EOS_dir`; do sed -i -e 's/EOS_dir/EOS_DIR/g' $i; done
```
