### ISSUE TITLE
Disallow change_max = 1.0 exactly

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#1863]
`castro.change_max = 1.0` means that the timestep can only ever stay the same or decrease relative to its initial value. I think we should disallow this value, I have a hard time imagining a use case for this (if you want a fixed timestep, use fixed_dt, and if you want a timestep cap but still allow the timestep to decrease, use max_dt). It causes problems with the retry functionality.

**Comment by zingale** [comment]
the following setups have change_max = 1.0:

gravity_tests/DustCollapse/inputs_pointmass
gravity_tests/hse_convergence
reacting_tests/bubble_convergence
radiation_tests/RadShestakovBolstad
