### ISSUE TITLE
Small plotfile and full plotfile code should be merged

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#192]
The shared code for generating small plotfiles and full plotfiles in Castro_io.cpp should be merged into a function called, say, writePlotFileCore(), since the code is almost all redundant. This will also prevent the two from getting out of sync; for example, the small plotfiles do not currently handle radiation the way that the full plotfiles do.

**Comment by zingale** [comment]
the small plotfile version seems inconsistent wrt particles.  It has some of the particle stuff in it, but not all.

**Comment by zingale** [comment]
this should keep the 2 separate functions (since they are virtual and hooked into AMReX), but each should call the same unified core routine.
