### ISSUE TITLE
Negative species should trigger a retry

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1952]
Right now we abort if any of the species are really negative in clean_state.  We should instead do a retry

**Comment by zingale** [comment]
this really seems to be an issue with SDC for S_new after we apply the sources

**Comment by zingale** [comment]
I think that the easiest way to do this is to have `clean_state` return a status, which indicates if that species check failed, and if it does, we modify the `advance_status status` variable accordingly in `Castro_advance_ctu.cpp`.

Thoughts?

**Comment by maxpkatz** [comment]
I prefer not to handle it exactly this way -- I would rather have it be that any update which updates the species checks at the time of the update whether it is creating an invalid state, and then reject the step at that point. Everything in clean_state() should be a backstop which resets the fluid state to something reasonable if all else fails, but we should be more rigorous about validating the output of the various updates.

Also, seems like an issue that we are only aborting in the CPU build for this error.

**Comment by zingale** [comment]
yes, we should abort on the GPU as well.  Does abort work there?

**Comment by maxpkatz** [comment]
It's not ideal to handle it that way -- the way to do it would be to reduce over the minimum and maximum X found, and apply the check after the parallel for.

**Comment by maxpkatz** [comment]
(We would still lose the print, although we could probably rewrite it to be a GPU-safe print since either way this kernel will not be that expensive.)
