### ISSUE TITLE
need a particle unit test

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#196]
We need to create a simple tracer particle unit test.  In Maestro, e.g., we initialize a bunch of particles with a circular velocity field and look to see if they complete an orbit correctly (there is no hydro, just a static velocity field).  Something like this would be useful for Castro.

**Comment by harpolea** [comment]
Added an implementation based on the test in MAESTRO in beb7e5c07b.

Below I've attached plots of the particles at t=0 and t = 2 * pi (i.e. after one complete rotation). They indicate that either there's a bug in the initialization of the velocity field or the particles are not being advected properly.

![particles_t0](https://user-images.githubusercontent.com/8247792/52746856-898d5000-2fb0-11e9-8469-e780e47d3a8f.png)
![particles_t2pi](https://user-images.githubusercontent.com/8247792/52746867-8c884080-2fb0-11e9-8893-dfefbe8851f1.png)
