### ISSUE TITLE
allow for plane-parallel 1/r**2 gravity

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1970]
We have a use for gravity that is plane-parallel but falls off as 1/r**2 from the center of a star.  You would supply M_star and R_star, and then compute gravity in the code as:

g = -Gm_star / (R_star + y)**2

for 2-d (replace y with z for 3-d).  The assumption is that the mass of the grid does not matter.

**Comment by maxpkatz** [comment]
Upon reflection this is best done as a modification to point-mass gravity rather than introducing a whole new option. The only thing we'd have to change is the denominator of the force calculation and the rest of the infrastructure could remain unchanged.

**Comment by zingale** [comment]
yes, that's a good idea.

**Comment by maxpkatz** [comment]
The code that adds a point mass to gravity is here: https://github.com/AMReX-Astro/Castro/blob/main/Source/gravity/Gravity.cpp#L2903-L2948

We have today
```
            Real rsq = x * x + y * y + z * z;
            Real radial_force = -C::Gconst * castro::point_mass / rsq;
```

`castro::point_mass` is the input parameter `castro.point_mass` and is defined in Source/driver/_cpp_parameters. To add the plane parallel functionality a new parameter should be added to _cpp_parameters, perhaps "point_mass_location_offset," which is the radial distance from the center and defaults to zero, and also an integer parameter "point_mass_is_plane_parallel" which is 0 by default. Then the new code might look like:

```
            Real rsq;
            if (point_mass_is_plane_parallel) {
                Real radial_dist = castro::point_mass_location_offset;
                if (AMREX_SPACEDIM == 1) {
                    radial_dist += x;
                }
                else if (AMREX_SPACEDIM == 2) {
                    radial_dist += y;
                }
                else {
                    radial_dist += z;
                }
                rsq = radial_dist * radial_dist;
            }
            else {
                rsq = x * x + y * y + z * z
            }
            Real radial_force = -C::Gconst * castro::point_mass / rsq;
```

The comments for `point_mass_location_offset` in _cpp_parameters should explain that this option only takes effect in the plane-parallel mode (or maybe it can be generalized to apply for the non-plane-parallel mode with some cleverness).

**Comment by aisclark91** [comment]
1. Just to catch up with the terminology; What do you mean by the plane parallel functionality? 

2. Is there an option to turn on the header ext_src.H in the makefile or is necessary to include it in the build directory?

**Comment by maxpkatz** [comment]
Normally when modeling a star, you'd compute the distance from the center for the purposes of computing the gravitational acceleration at the star's surface. In Cartesian coordinates, assuming the star's center is at the origin, the distance would be a function of x, y, and z. But in a plane parallel simulation you're zooming in on a small patch of the surface of the star, small enough that you can assume curvature effects don't matter, and moving vertically away from the center is physically equivalent to moving radially away from the center of the star. In the simulation coordinates only one axis (e.g. y or z) would measure that vertical distance.

ext_src.H will automatically be overriden with the local copy you provide in the problem directory.

**Comment by aisclark91** [comment]
I see, I suppose the criteria for the patch depends on the max size between the points of the patch and Rd\theta where d\theta is fixed?

**Comment by zingale** [comment]
this was added in #1981
