### ISSUE TITLE
implement an "establish convective field" option

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#1994]
Long ago, in MAESTRO, we had an option where we would let the reactions establish a convective field without letting the temperature increase, and therefore avoiding running away in place.  We did this by using the base state temperature in calling the reactions up to a point and then we flipped a switch, and let the system evolve self-consistently.

We could imagine implementing this in Castro by burning using the T from the initial model instead of the grid T and then once the convective field is established, changing back to the grid temperature.

**Comment by zingale** [comment]
actually, we might have remapped the initial model but kept the velocity field once we built up a velocity field.

**Comment by zingale** [comment]
here's a proposed implementation.

two new runtime parameters:

* `drive_initial_convection` : if this is set to 1, then when we call the network, we interpolate T from the initial model instead of using the value on the grid.  This prevents the nonlinear feedback on enuc from increasing T as we burn in place

* `restart_after_convective_initialization`: this is used after we've run for some time with `drive_initial_convection` and have an established velocity field on the grid.  This takes effect on restart.  We read the checkpoint as normal but then if this is set to 1, we call the initialization routine again to remap the thermodynamic data.  It will be the responsibility of the problem setup to check for `restart_after_convective_initialization`, and if it is 1, skip the velocity initialization, since we will already have filled it from checkpoint.

**Comment by zingale** [comment]
Aside: we could take the simpler approach of just resetting S_new to S_old (except for the velocity) after each update, but I think that this will not drive convection, because we'll lose the buoyancy.

**Comment by zingale** [comment]
actually, this is quite tricky with SDC... need to think about this some

**Comment by zingale** [comment]
I think the best way to do this for SDC is to add a field to burn_t that is something like `fixed_T` and if `fixed_T > 0` we use it instead of the T derived from (rho e) and the EOS.

**Comment by maxpkatz** [comment]
As long as you don't care about the nonlinearity within a single burn step, you could do this in Castro by jus resetting T to its value from before the burn in react_state.

**Comment by zingale** [comment]
but that will change e and P and therefore take us out of HSE.  I really only want to change the T that reactions see.

**Comment by zingale** [comment]
My new thinking is that we should be allowed to specify a frequency at which we reinitialize the state data (aside from the velocity field) and also a maximum time for which we should drive initial convection.  Then we can do the driving for say 20 second, with a reinit of the thermodynamics every second, and after 20 seconds we'll be running as if from t = 0 with a fully-realized (?) velocity field.

**Comment by zingale** [comment]
I can imagine the reset of the data taking place either in `postCoarseTimeStep` or `initialize_advance`

**Comment by zingale** [comment]
this has been done now in #1998
