### ISSUE TITLE
flame_wave taking much smaller steps than 21.06

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2010]
Sometime between 21.06 and now, the size of the timestep for a 2-d flame_wave problem seems to have decreased by a factor of 2 or more

`21.06-41-gf589dd44f` : 
```
STEP = 2000 TIME = 0.0003829310843 DT = 6.434917763e-08
```

`21.09-32-ga26cd39dd` : 
```
STEP = 2000 TIME = 0.0001437788864 DT = 5.912092337e-08
```

this issue will be used to track this change

**Comment by zingale** [comment]
the issue seems to come after `21.09`

first plotfile (5.e-4 s) step number:

`21.06-xxx` : 2565
`21.07` : 2855
`21.08` : 2878
`21.09` : 2878
`development` : 6894

**Comment by yut23** [comment]
Whatever caused this doesn't seem to have affected the 1000Hz H/He setup. I'm getting:
`21.06` : 4157
`21.08` : 4104
`development` : 4104 (same time as `21.08` exactly)

**Comment by zingale** [comment]
note, that with Castro on development, but Microphysics on 21.09, I don't have the problem.

So it seems like it is an issue in Microphysics?  probably related to iso7.

**Comment by zingale** [comment]
we work fine with Microphysics 21.09-1-g744e8e6d

**Comment by zingale** [comment]
okay it seems to be an issue with Microphysics 21.09-10-g3aeed203

```
commit 3aeed2036de9d945856a324c9beb95a8dafaeb9f
Author: Max Katz <maxpkatz@gmail.com>
Date:   Wed Sep 15 08:19:56 2021 -0700

    iso7 28/∞ (#767)
    
    Adds a function to automatically compute density dependence of tabulated rates.
    
    The Ca40 + He4 <-> Ti44 rate is not dealt with yet since it doesn't have an entry in rhs_data().

```

**Comment by zingale** [comment]
indeed, git bisect confirms that is the commit that causes the problems on Summit.

I don't see anything wrong that that issue, but maybe the GPU doesn't like it?

**Comment by zingale** [comment]
closing this, as we've been running flame_wave without issue lately.
