### ISSUE TITLE
Trouble running on Perlmutter

### ISSUE THREAD

**Issue by MargotF** [AMReX-Astro/Castro#2017]
I have not been able to successfully run Castro on the Perlmutter GPUs. 

At the head of the output file are multiple warnings:

-----------------

Multiple GPUs are visible to each MPI rank, but the number of GPUs per socket or node has not been provided.

--------------------

And then while running the simulation crashes with negative densities. 

To compile, I am following the Perlmutter compile instructions to the t: 

-------------------------

module load PrgEnv-gnu
module load gcc/9.3.0
make -j COMP=gnu TINY_PROFILE=TRUE USE_MPI=TRUE USE_OMP=FALSE USE_CUDA=TRUE NVCC_CCBIN=CC

-------------------------

and have confirmed environment variables are correctly set.

Batch file looks like:

-----------------------

#!/bin/bash                                                                     
#SBATCH -A m2218_g                                                              
#SBATCH -C gpu                                                                  
#SBATCH -q regular                                                              
#SBATCH -t 3:00:00                                                              
#SBATCH -n 16                                                                   
#SBATCH --ntasks-per-node=4                                                     
#SBATCH -c 16                                                                   
#SBATCH --gpus-per-task=1                                                       

export OMP_PROC_BIND=true
export OMP_PLACES=cores
export OMP_NUM_THREADS=1
srun --cpu-bind=cores ./Castro1d.gnu.TPROF.MPI.CUDA.ex inputs

------------------------

Any help with this issue is appreciated.

**Comment by zingale** [comment]
were you able to give this a try @MargotF ?

**Comment by MargotF** [comment]
I just gave it a go. Now I seem to be getting a different error:

---------------

amrex::Abort::13::CUDA error 100 in file /pscratch/sd/m/margotf/Castro/external/amrex/Src/Base/AMReX_GpuDevice.cpp line 166: no CUDA-capable device is detected !!!

------------------

I have never tried using that with Cori. My understanding is that that command binds one GPU to each task, rather than making all GPUs visible to all tasks....which seems like it would cause problems sharing different parts of the grid. Maybe I do not have the right understanding, though.

**Comment by zingale** [comment]
is there any update on this? otherwise, I think we'll close this issue.

**Comment by maxpkatz** [comment]
OK thanks. Feel free to reopen if you try to run on Perlmutter again and need help.
