### ISSUE TITLE
Institute a velocity limiter

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#203]
The code does not know that grid velocities should not be larger than the speed of light. This can and does therefore happen sometimes, particularly in low-density material near sharp density gradients. We should institute a limiter that prevents velocities from reaching c. Better still would be to prevent it from reaching some fraction of c, like 0.1c.

**Comment by maxpkatz** [comment]
Or, if not, we should warn the user or crash when we get superluminal.

**Comment by zingale** [comment]
I don't think we should do this -- we do not have a relativistic solver, so we run the risk of being inconsistent.  People can sponge if they wish.
