### ISSUE TITLE
burning problems on Perlmutter

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2080]
When running a problem with reactions on NERSC Perlmutter, we seem to encounter too many subcycles.  It seems that the burn is not working properly (Castro reports that the burn was unsuccessful).

You can reproduce this as follows:

```
module load PrgEnv-gnu cudatoolkit
```

in `Castro/Exec/science/subchandra`:

```
make NETWORK_DIR=subch USE_CUDA=TRUE COMP=gnu -j 8
```

run with `inputs_2d.N14` using:

```
#!/bin/bash
#SBATCH -A m3018_g
#SBATCH -C gpu
#SBATCH -J Castro
#SBATCH -o sedov_%j.out
#SBATCH -t 1:00
#SBATCH -N 4
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=map_gpu:0,1,2,3

srun -n 16 ./Castro2d.gnu.DEBUG.MPI.CUDA.ex inputs_2d.N14 castro.time_integration_method=0 integrator.atol_spec=1.e-5 integrator.jacobian=2
```

**Comment by zingale** [comment]
the same issue happens if we run with SDC

**Comment by zingale** [comment]
I'm able to get through a bit of burning when running with cuda-memcheck (I time out before the crash seen above)

**Comment by zingale** [comment]
The same problem occurs with version 21.12 of the code (that is the first tag where the C++ subch net is available)

**Comment by zingale** [comment]
flame_wave seems to work with inputs_2d.testsuite even if I bump to `amr.max_level=2`
maybe this is a sub-chandra problem?

**Comment by zingale** [comment]
update: this problem works fine on groot (Titan V), so there is something odd with Perlmutter

**Comment by zingale** [comment]
I don't seem to have problems one 1 GPU on Perlmutter (it does fail a burn but recovers without taking too many subcycles).

So maybe there is an MPI issue?

**Comment by zingale** [comment]
running the problem with `compute-sanitizer` didn't turn up any issues

**Comment by zingale** [comment]
Note we still hit the problem if we compile with `DEBUG=TRUE`

**Comment by zingale** [comment]
dropping down to `CUDA_ARCH=70` doesn't fix things

**Comment by zingale** [comment]
running this on groot (on CPU) with valgrind also turns up no issues

**Comment by maxpkatz** [comment]
I can reproduce an issue with that setup even with reactions turned off. When I use a single GPU, the hydro timestep calculation matches the single-rank or multi-rank CPU version, but a multi-rank GPU build results in a hydro timestep that starts drifting after the first step and crashes with too many subcycles by step 7. The multi-rank GPU runs are deterministic (at least in the timestepping), they just don't match the single-rank case.

```
srun -n 4 ./Castro2d.gnu.MPI.CUDA.ex inputs_2d.N14 castro.time_integration_method=0 integrator.atol_spec=1.e-5 integrator.jacobian=2 castro.do_react=0 amr.max_level=1 castro.do_sponge=0 castro.do_grav=1 castro.do_hydro=1 max_step=10
```
