### ISSUE TITLE
data loading issue when using yt for visualization

### ISSUE THREAD

**Issue by zhichen3** [AMReX-Astro/Castro#2081]
![image](https://user-images.githubusercontent.com/62574124/152657111-512bc9f6-35ff-4878-b21f-d1a51b6d31b3.png)

There is an issue when using `ds = yt.load(plotfile)` for Castro output files for visualization.

One possible solution is to use the method below instead of `yt.load(plotfile)`: 
`from yt.frontends.boxlib.api import CastroDataset`
`ds = CastroDataset(plotfile)`

**Comment by zingale** [comment]
I think that newer yt versions also have a `hint` keyword, so `ds = yt.load(plotfile, hint="castro")` should work too

**Comment by zingale** [comment]
I think that this is resolved now
