### ISSUE TITLE
Hydro update does not update State_Type ghost zones

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#213]
Essentially the entire CTU advance scheme as it currently written assumes that the state has zero ghost zones, but this is an incorrect assumption when using radiation. This means that the data in the ghost zone is invalid. We need to go through and apply the source terms and hydro source to the state including on its ghost zones.

**Comment by maxpkatz** [comment]
I believe this explains the issue @taehoryu has observed with trying to calculate derived variables like magvort and divu when using radiation. In that case, the "source" MultiFab has a ghost zone so we can calculative gradients/curls, and since the state does too, it will try to fill from that ghost zone (unlike most other derived routines, where FillPatch will use appropriate BC fills because the source MF does not have any ghost zones).

**Comment by zingale** [comment]
this might be related to #116 too

**Comment by maxpkatz** [comment]
The easiest solution here is, from a programming point of view, if we have all source terms merged into a single MultiFab that has no ghost zones (#165), we can do a fillpatch to expand it to as many ghost zones as there are state values.

Avoiding a communication step would be preferred. But to do that right, we need to have the Poisson gravity solution in multiple ghost zones, which we are not currently set up to do.
