### ISSUE TITLE
Castro dies with ROCm 5.x

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2136]
We run fine with ROCm 4.5.0, but with 5.x, we get errors like:

```
Initializing the data at level 0
Done initializing the level 0 data
Memory access fault by GPU node-11 (Agent handle: 0x2c5d5e0) on address (nil). Reason: Page not present or supervisor privilege.
Memory access fault by GPU node-6 (Agent handle: 0x2c5d5e0) on address (nil). Reason: Page not present or supervisor privilege.
Memory access fault by GPU node-4 (Agent handle: 0x2c5d620) on address (nil). Reason: Page not present or supervisor privilege.
Memory access fault by GPU node-11 (Agent handle: 0x2c5d5e0) on address (nil). Reason: Page not present or supervisor privilege.
```

this happens both with `Sedov` and `flame_wave`.  Nyx is not affected, so there is something we are doing that seems to be an issue.

**Comment by WeiqunZhang** [comment]
`extern __manged__` works in my simple test https://github.com/WeiqunZhang/amrex-devtests/tree/main/hip_extern.

**Comment by zingale** [comment]
If I run with ROCm 5.1 using `subchandra`, compiled as:

```
module load PrgEnv-amd craype-accel-amd-gfx90a rocm/5.1.0
make USE_SIMPLIFIED_SDC=TRUE COMP=gnu USE_HIP=TRUE DIM=3 NETWORK_DIR=aprox19 -j 4
```

then by using `AMREX_DEVICE_PRINTF`, the crash happens in the EOS call in `problem_initialize()` -- this is probably the first EOS call we do.

**Comment by zingale** [comment]
things seem to be fixed with https://github.com/AMReX-Astro/Microphysics/pull/929

I ran:

* `test_react` with `subch_approx`
* `Sedov` in 3-d
* `subchandra` in 2-d

without any issues on crusher with ROCm 5.1.
