### ISSUE TITLE
GPU CI action fails

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2154]
We seem to be asking for an older version of CUDA / Ubuntu:

https://github.com/AMReX-Astro/Castro/blob/main/.github/workflows/gpu_action.yml

**Comment by yut23** [comment]
See https://forums.developer.nvidia.com/t/invalid-public-key-for-cuda-apt-repository/212901/10

**Comment by zingale** [comment]
fixed in #2155
