### ISSUE TITLE
NQ >= NUM_STATE assumption in SDC is not true when HYBRID_MOMENTUM=TRUE

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#2156]
The copy from S_new into S_noreact for simplified SDC assumes that NQ >= NUM_STATE, as noted in this comment:

https://github.com/AMReX-Astro/Castro/blob/910da6ab7db14af3e940f0d4caa2ad5050e0c5d6/Source/driver/Castro_advance_ctu.cpp#L340-L344

This is not true when USE_HYBRID_MOMENTUM=TRUE, because that adds three new conserved state variables which don't have any primitive counterpart. So this code will result in out-of-bounds accesses.

**Comment by maxpkatz** [comment]
Maybe at this point we can have `Simplified_SDC_React_Type` be of size `NUM_STATE`?

**Comment by zingale** [comment]
maybe just `max(NUM_STATE, NQ)`?

**Comment by maxpkatz** [comment]
I'm more worried about making sure we understand and clearly document what quantity is in that state type, so that there can be no ambiguity about whether it is NQ or NUM_STATE.

**Comment by zingale** [comment]
yes, I agree.  This is clearly a hack -- and indicated as such in the comments.  I will think about this.

It would be nice to be able to attach a piece of metadata to a MF so we could query it (like `is_conserved_state`, `is_thermo_consistent`, ...)

**Comment by maxpkatz** [comment]
Documenting the current behavior:

- We do the hydro step, using SDC sources that are stored in Simplified_SDC_React_Type (which at that point refer to primitive quantities)
- We store U + dU_hydro into Simplified_SDC_React_Type, so at this point it's a conservative MultiFab
- We do the SDC burn to get (U + dU_hydro + dU_burn)
- After the burn we compute the primitive version of (U + dU_hydro), then the primitive version of (U + dU_hydro + dU_burn), and store the difference in Simplified_SDC_React_Type

**Comment by maxpkatz** [comment]
Assuming I have this right, I think we can solve this problem by doing the calculation of Simplified_SDC_React_Type inline in react_state. At the beginning of react_state, we could compute a local copy of (U + dU_hydro) converted to primitive variables and store it in thread-local memory, then we could do the burn, then we could convert the burn contribution to primitive variables, and then store the difference in Simplified_SDC_React_Type. Then we'd never explicitly be storing the conserved state in this container, so the problem should go away.
