### ISSUE TITLE
Cannot compile the flame problem with "USE_SDC=TRUE"

### ISSUE THREAD

**Issue by KISSFORMISS** [AMReX-Astro/Castro#216]
I'm studying the flame model in Castro recently. I would like to compare the SDC method to Strang splitting method we usually used. But when I tried to compile with "USE_SDC=TRUE", it failed with following error message:

Error: Symbol 'eos_get_small_dens' referenced at (1) not found in module 'eos_module'
/home/muhung/Microphysics/integration/BS/bs_type_sdc.F90:56.45:

    use eos_module, only: eos_get_small_dens, eos_get_max_dens, eos
                                             1
Error: Symbol 'eos_get_max_dens' referenced at (1) not found in module 'eos_module'
Compiling riemann_1d.F90 ...
/home/muhung/Microphysics/integration/BS/bs_type_sdc.F90:301.30:

    use eos_module, only: eos, eos_get_small_temp, eos_get_max_temp
                              1
Error: Symbol 'eos_get_small_temp' referenced at (1) not found in module 'eos_module'
/home/muhung/Microphysics/integration/BS/bs_type_sdc.F90:301.50:

    use eos_module, only: eos, eos_get_small_temp, eos_get_max_temp
                                                  1
Error: Symbol 'eos_get_max_temp' referenced at (1) not found in module 'eos_module'

**Comment by zingale** [comment]
this is because the `BS`  integrator doesn't build anymore with SDC, but `VODE` is preferred anyway.  I'll switch it to VODE.

**Comment by zingale** [comment]
actually, BS is the backup integrator, so we need to fix things there

**Comment by zingale** [comment]
this is fixed in StarKiller: https://github.com/starkiller-astro/Microphysics/pull/57

**Comment by zingale** [comment]
this has been fixed by a combination of me and @dwillcox
