### ISSUE TITLE
Density flux limiter does not help when there are multiple large negative fluxes

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#2182]
Consider the following scenario in 1D. A zone has density rho = 1.0, the timestep is dt = 1.0, the zone size is 1.0 (in arbitrary units). The update to the zone is drho = F_{i-1/2} - F_{i+1/2}. Now imagine that due to some pathological scenario, we have F_{i-1/2} = -1.0 and F_{i+1/2} = +1.0, so that both ends of the zone are trying to evacuate. This would, on its own, lead to rho = -1.0, resulting in a retry (eventually dt would be small enough that the update will leave the density positive). If we are using castro.limit_fluxes_on_small_dens, this will be intercepted and the fluxes will be limited. Let's assume small_dens = 1e-6. In the current scheme, as of #2134, the hydro limiter will work to ensure that each zone on its own does not result in a density that is smaller than 2e-6. So each flux will be limited to (1.0 - 2e-6). But when the sum of these two effects is added together, the zone goes negative. Both fluxes need to be limited much more strongly in this case, by at least a factor of 2. The problem is that the current algorithm evaluates each flux independently, without information from other fluxes going into the same cell.

This problem was identified in #2123 and addressed in the reflux calculation, where the evalution is done on a zone center basis rather than zone face basis, so that the sum of the fluxes could be seen all at once. However, this only works safely in parallel if there aren't multiple threads talking to the same zone face. This assumption is not correct in the general hydro update case (though it is correct in the reflux case).

So some work is needed to be done to improve the limiter for this case. Although the scenario above is not a real example, this scenario seems to happen somewhat often at sharp density gradients near the edge of stars -- since these are curved surfaces, there could be sharp gradients in multiple dimensions, leading to multiple large negative fluxes.

**Comment by maxpkatz** [comment]
One idea that allows us to continue operating on a cell face basis, but still consider multiple nearby edges, is to look at the edge values for q that come out of the Riemann solver. The paper that the flux limiter was originally based on proposed, as one variant of the method, scaling the flux limits in multiple dimensions by the cell-center velocity in each direction (so that if the flow was predominantly in one direction, that direction would be limited more strongly). So extending this a bit, we can look at qe for each of the faces touching the two cell centers that would be updated by a given flux, and scale this flux down by the ratio of the velocity of this flux relative to the sum of the velocities of all of the outgoing fluxes. (The flux on the passives is linear in that edge velocity, so I think this works out.) This is thread-safe because we don't update the edge velocities themselves in the flux limiter, only the fluxes.

**Comment by zingale** [comment]
has this been addressed now?

**Comment by maxpkatz** [comment]
It is no longer a problem, however I am not particularly happy with the solution I implemented. That said, I'm not likely to spend more time on this problem in the near-term.
