### ISSUE TITLE
QOL suggestions for examples based on v22.05 

### ISSUE THREAD

**Issue by KedoKudo** [AMReX-Astro/Castro#2245]
As part of our proxy I/O app project, we ran most of the existing examples from CASTRO_V22.05 and found some common issues:

- a lot of the makefiles are not updated (e.g. missing `USE_TRUE_SDC=TRUE`)
- some examples are too big to run even on summit
- some code no longer compiles (various API errors)
- some examples could benefit from an example job script to indicate
  - what is the minimum requirement for memory
  - what is the minimum requirement for CPU/GPU
- some examples could not reach convergence at first increment (the default input parameter needs to be updated)
- some examples seem to be related to published journal articles, and it would be great if the corresponding DOI can be found in the Readme file.

More details can be found in this report
[Castro_V22.05_issue_report.pdf](https://github.com/AMReX-Astro/Castro/files/9143469/Castro_V22.05_issue_report.pdf)

**Comment by zingale** [comment]
USE_TRUE_SDC should not be used for all problems.  It did not support AMR or all the physics, so I am confused why you mention that option.  Are there other options that you think are missing?

Also, I am not aware of any examples that don't fit on Summit, can you give more details?

A lot of the science problems have job scripts, but some were probably only ever run on local workstations, so there are no scripts to add.  Usually it is best to contact us if you want details of how to beat run something, and we can help out.  If there are specific problems you are interested in, please let us know.

I agree about the DOIs.  I will try to add them in the future

**Comment by KedoKudo** [comment]
Thanks for the quick response.  The detailed info are in the attached pdf report.  But I can highlight a few here:

- In `reacting`, most of the examples will trigger an error if the binary is not compiled with `USE_TRUE_SDC=TRUE`.  The same goes for some of the examples in `science`

- In `radiation`, the example `RadSuOlson` will lead to a memory error during runtime, even if the job is submitted to batch-hm.

**Comment by zingale** [comment]
thanks.  Looking at the report, even though most of the inputs files might use `USE_TRUE_SDC=TRUE`, that does not mean that we want it on by default.  Those inputs files are in various stages of testing for improvements to the SDC method and for forthcoming papers in the next few years.

Likewise with the subchandra, there is not much guidance there on how to run things because it is under active development and we've never published a paper with it (but hope to in the next months).

I will look at the radiation + CUDA.  I'll note that we have one test in our nightly test suite that exercises radiation + CUDA:
http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2022-07-19/rad-SuOlson.html

but there are likely cases that are not exercised well.

**Comment by zingale** [comment]
for the comment that wdmerger requires more memory than summit can provide.  Does this mean that if you use all 4600 nodes on Summit, it still cannot fit the problem?  Because that is not our experience.

**Comment by KedoKudo** [comment]
> 
We did not request 4600 nodes for our test.  If I remember correctly, we requested 4 nodes for our test.

BTW, do you happen to know what is the minimum number of nodes it needs to run?

**Comment by KedoKudo** [comment]
> I think it depends on the problem. We run nightly on a single GPU here:
> 
> http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2022-07-19/wdmerger_3D.html
> 
> one would also need to increase the number of nodes as the problem becomes more complex. I would bet for science runs that something like 64 - 128 nodes would be the starting point.

Great, thanks for the info :smile:

**Comment by zingale** [comment]
I think that most of these have been addressed now.  Thanks for the suggestions.
