### ISSUE TITLE
Performance regression since 2015

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#226]
When running the 3D RT problem from June 2015, I observed that the single-core performance was about 50% slower using the current code. I need to figure out what contributed to this, likely by bisecting.

**Comment by maxpkatz** [comment]
I am running this with

./Castro3d.Linux.g++.gfortran.ex inputs_3d amr.n_cell=128 128 128 geometry.prob_hi=0.5 0.5 0.5 max_step=10 amr.max_level=0

**Comment by maxpkatz** [comment]
This happened between 16.08 and 16.09.

**Comment by zingale** [comment]
next step would be to see if it is an Castro thing (highly likely) or AMReX.  Does 16.08 Castro work with 16.09 AMReX and show the same performance?

**Comment by zingale** [comment]
some of this seems to be GNU-specific.

**Comment by zingale** [comment]
this is now 2 years old.  Closing this as we already have issues opened about profiling and performance monitoring.
