### ISSUE TITLE
Is it Possible to Relocate Plots?

### ISSUE THREAD

**Issue by joehellmers** [AMReX-Astro/Castro#2274]
I'm running out of disk space when running certain simulations.

Is it possible to relocate the plot files to another location?

I tried this

```
maestro.plot_file  = /home/jhellmer/plt
amr.plot_file = /home/jhellmer/plt
```
But this didn't seem to have any effect.
NOTE: I know this if for MAESTROeX, but there doesn't seem like there is a lot of activity over there, so I'm posting here.

**Comment by zingale** [comment]
you should be able to rename it that way, but to be honest, I always just copy the executable and any necessary files into a directory on the disk I intend to run from.

**Comment by maxpkatz** [comment]
In MAESTROeX the parameter you're looking for is `maestro.plot_base_name`.

**Comment by joehellmers** [comment]
@maxpkatz, thanks, that works.

I didn't see it because apparently it gets embedded to the file `maestro_params.H` when building the executable.

**Comment by joehellmers** [comment]
@zingale I'm trying to do something similar in Castro, but it still isn't working?

Is something like this correct?

`mpirun -n 64 Castro2d.gnu.MPI.SMPLSDC.ex inputs_2d.NSE castro.max_subcycles=30 castro.plot_base_name=/expanse/lustre/projects/sdu131/jhellmer/subchandra`

It doesn't seem to be working.

Also, is it possible to do something similar for the check point folders?

**Comment by zingale** [comment]
can you share more details? what is not working? are you sure that directory exists and is visible from compute nodes?

**Comment by zingale** [comment]
also, where did you find `castro.plot_base_name` -- that option doesn't exist.

you should try `amr.plot_file`

**Comment by joehellmers** [comment]
I sort of assumed that Castro has an option like the Maestro example from above.

Setting the amr_file as below is working well.  It seems to act sort of like a prefix

`mpirun -n 64 Castro2d.gnu.MPI.SMPLSDC.ex inputs_2d.NSE castro.max_subcycles=30 castro.plot_base_name=/expanse/lustre/projects/sdu131/jhellmer/subchandra/plt`

Thanks for your help!

Is there a way to relocate the location of the check points?  I guess I could just turn off check point perhaps?

**Comment by joehellmers** [comment]
`amr.check_file` looks like the way to do it.
