### ISSUE TITLE
build fails with libquadmath link error on arm

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Astro/Castro#2293]
I am trying to build the RadBlastWave problem on Fedora 37. However, I get:

```
/usr/bin/ld: cannot find -lquadmath: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [../../../external/amrex/Tools/GNUMake/Make.rules:56: Castro3d.gnu.MPI.ex] Error 1
```

I have gfortran installed, so I'm not sure how this is happening.

**Comment by zingale** [comment]
do you have the libquadmath package installed? https://packages.fedoraproject.org/pkgs/gcc/libquadmath/fedora-37.html

**Comment by aisclark91** [comment]
Just as a mere suggestion, try the following:

1. Clone the external repositories (Microphysics and amrex) in your local machine. Define the environment variables `MICROPHYSICS_HOME` and `AMREX_HOME` in .bashrc, with their locations. Clone Castro and do not use the `--recursive` while cloning it. Finally define the variable `CASTRO_HOME` with the location of Castro.

2. Change Microphysics and Castro into the development branch. amrex by default should be in development.

3. Repeat the compilation process.

**Comment by BenWibking** [comment]
> do you have the libquadmath package installed? https://packages.fedoraproject.org/pkgs/gcc/libquadmath/fedora-37.html

It doesn't appear to exist on aarch64:
```
[benwibking@lima-fedora benwibking]$ dnf info libquadmath
Last metadata expiration check: 1:30:29 ago on Thu 03 Nov 2022 06:50:55 PM UTC.
Error: No matching Packages to list
```

**Comment by BenWibking** [comment]
I should add I'm running on an M1 MacBook, so maybe no one has tested Linux/arm64 yet.

**Comment by zingale** [comment]
I don't think anyone around here has a Mac.  But I suspect this is an AMReX
issue, since we just use their build system

**Comment by BenWibking** [comment]
I can open an issue about building with Fortran support on linux/arm64 in the AMReX github.

**Comment by BenWibking** [comment]
Does Castro need Fortran support for the radiation code?

**Comment by zingale** [comment]
yes, but only because we've been too lazy to finish porting it to C++

**Comment by BenWibking** [comment]
This will fix it: https://github.com/AMReX-Codes/amrex/pull/3018
