### ISSUE TITLE
'mf_linear_slope_minmax_interp’ was not declared

### ISSUE THREAD

**Issue by Tom-Y-Liu** [AMReX-Astro/Castro#2336]
Hi, 

I get the following error message when trying to run Castro examples on a remote Linux machine. 

![image](https://user-images.githubusercontent.com/55120383/212174690-dc8e896a-8945-441f-a3ee-948681ad6621.png)

The problem can be solved by simply commenting out line 345 in Castro_setup.cpp. Is it a universal issue that happens to all users? Or it is just for me?

I am using:
 - gcc/10.2.0
 - openmpi/4.1.1

**Comment by zingale** [comment]
can you make sure that your AMReX is up-to-date?  That feature was added to AMReX back in November.

**Comment by Tom-Y-Liu** [comment]
Hi Michael,

You are right. The AMReX I was using is outdated. The problem is solved by pull the most recent AMReX.

Thanks,
Yinmin
