### ISSUE TITLE
SDC second-order?

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#236]
From Marc:

> I’m looking into why some of my variables are only first order accurate in PeleC, and so I’m digging through the latest version of Castro’s SDC implementation for clues.  In setting up the source term for the hydro, there is a note to time-center the sources, and in that, the sources_for_hydro += SDC_Source_Type.  Is there a 1/2 factor missing?  Seems like the source started as the sum of the old- time non-reacting sources, and you added the new time sources (computed from the previous SDC iteration), but it seems like you then should scale by 1/2.  No?

**Comment by maxpkatz** [comment]
In Castro the "new-time" sources are actually the corrector part of a predictor-corrector. So adding the new sources to the old sources is subtracting half of the old-time value from the predictor (which was the full old-time value) and adding half of the new-time value. So the end result is time centered. That comment Marc is referring to used to have another sentence explaining that point, but for some reason I apparently deleted this second sentence at some point.
