### ISSUE TITLE
MGFLD lab frame flux

### ISSUE THREAD

**Issue by Saligiare-pwd** [AMReX-Astro/Castro#2413]
Dear all,
I have been trying to Output lab frame flux when MGFLD is in used, but the results are all zero in Frlab_nx.
I am running modified shock breakout test problem, other test problem with MGFLD also can not output lab frame flux information (comoving flux works well).
Is there anything that I might missed?

Thank you!

**Comment by Saligiare-pwd** [comment]
Thank you!
I also receive same error if I plot both 

radiation.plot_com_flux=1

radiation.plot_lab_flux=1

My initial guess is that in MGFLDRadsolver.cpp:

  if (plot_com_flux) {
      flxcc = plotvar[level].get();
      icomp_flux = icomp_com_Fr;
  } else if (plot_lab_Er || plot_lab_flux) {
      flxsave.reset(new MultiFab(grids, dmap, nGroups*AMREX_SPACEDIM, 0));
      flxcc = flxsave.get();
      icomp_flux = 0;
  } 

Which might skip plotting lab_flux if com_flux is needed?

**Comment by Saligiare-pwd** [comment]
Dear all,
The file corrects the 2D problem!
But for 3D, I get the following error when outputting lab frame flux.

amrex::Abort::7:: (32,32,32,16) is out of bound (32:47,32:47,32:47,0:11) !!! 
SIGABRT
amrex::Abort::0:: (0,0,0,16) is out of bound (0:15,0:15,0:15,0:11) !!! 
SIGABRT
amrex::amrex::Abort::1:: (32,0,0,16) is out of bound (32:47,0:15,0:15,0:11) !!! 
Abort::5:: (32,0,32,16) is out of bound (32:47,0:15,32:47,0:11) !!! 
amrex::SIGABRT
Abort::SIGABRT
6:: (0,32,32,16) is out of bound (0:15,32:47,32:47,0:11) !!! 
SIGABRT
amrex::Abort::2:: (0,32,0,16) is out of bound (0:15,32:47,0:15,0:11) !!! 
amrex::amrex::Abort::Abort::4:: (0,0,32,16) is out of bound (0:15,0:15,32:47,0:11) !!! 
3:: (32,32,0,16) is out of bound (32:47,32:47,0:15,0:11) !!!

**Comment by zingale** [comment]
can you tell me how to reproduce this?

**Comment by zingale** [comment]
okay, I can reproduce.  I think that the original code was wrong (even before #1700) in how we were computing the offset for the flux storage.  I'll do a PR to the PR

**Comment by maxpkatz** [comment]
@Saligiare-pwd could you please try again on the latest version of the development branch?

**Comment by Saligiare-pwd** [comment]
Dear all,
The new branch fixes the above problems!
Thank you very much for solving this.

**Comment by Saligiare-pwd** [comment]
The lab frame flux is produced without further error with the branch mentioned.
