### ISSUE TITLE
have reaction loop print out failures even when on GPU

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2515]
Currently, when running on the GPU, the different integrators do not print out the failures.  But we now have standardized error codes, which we can add to the `burn_t`.  Then we can store these in Castro to output once we leave the GPU kernel. 

Some of this is discussed here:

https://github.com/AMReX-Astro/Microphysics/issues/705

**Comment by zingale** [comment]
In an ideal world, we'd setup a `vector<burn_t>` in Castro outside of the loop over the MF and then push back the burn_t of any zone that fails.  Then outside of the GPU kernel, we'd loop over the vector and print out the failures.

This can really help with debugging.

Is there a way to do this easily with GPUs?

**Comment by maxpkatz** [comment]
If you add the error code as a burn_t member, there's a couple ideas I have here for how to do some version of this.

**Comment by zingale** [comment]
the error codes are added to the burn_t in this PR:
https://github.com/AMReX-Astro/Microphysics/pull/1254

**Comment by zingale** [comment]
this is addressed now if we build with USE_GPU_PRINTF=TRUE
