### ISSUE TITLE
don't trace under sources that are zero

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#256]
when we fix #9, we will treat all sources consistently in hydro.  But since we have a source for every state variable, there will be a lot of needless work for equations that have no sources (e.g. density, usually, and species).  So we should check if the norm0 of the source is 0, and if so, skip the ppm reconstruction and tracing of the sources.  This will save on flops.

It is better to do it this way that to just assume certain sources are zero, since the user can have time-dependent external sources.  So we need to check each step.

**Comment by maxpkatz** [comment]
Note: to save on parallel communication, I think we should do this with the `local` option of norm0. Whether we do the PPM on this FAB has nothing to do with whether we do it on some other FAB. Also, we need to remember to do it on the ghost zones too.

**Comment by zingale** [comment]
some of this will be mitigated by #350
