### ISSUE TITLE
split c-linter action in 2

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2746]
Right now the c-linter action does clang-tidy and claims to do cppcheck.  We should split it in two.

For the clang-tidy, we should use the build process that is in AMReX currently (`USE_CLANG_TIDY=TRUE`).

For cppcheck, we should make sure it is actually running and make an artifact from the output.

**Comment by yut23** [comment]
One of the considerations is that cppcheck uses a compilation database to pick up the right options and files. It might be possible to do something with `make print-CXXFLAGS` etc instead, but I'm not sure.
