### ISSUE TITLE
MHD needs species

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#278]
The MHD solver does not consistently handle species.

In particular:

  * `mhd_plm_3d.f90` does not trace species (and they are not present at all in the eigensystem
  * `hlld.f90` does not solve the Riemann problem for species -- we can have them behave in the same way that the transverse velocities do
  * `ct_upwind.f90` does not do corner coupling for the species

There may be more places

**Comment by zingale** [comment]
I think this is done now, right @guadabsb15 ?

**Comment by guadabsb15** [comment]
yes!
