### ISSUE TITLE
still have issues with pressure in 1-d momentum fluxes

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2803]
It looks like we adding the pressure  to the momntum flux in 1-d Cartesian in `scale_flux()`, but I think this is wrong -- it should already be added since `mom_flux_has_p` is always true for Cartesian.  So I think that we need to remove this addition in `advection_util.cpp`

**Comment by zingale** [comment]
it looks like this was missed in #2468

**Comment by zhichen3** [comment]
I agree that the addition should be removed. #2468  makes `mom_flux_has_p` to return true instead of false for 1D cartesian, which is certainly the correct behavior. So now pressure is already included in the definition of flux in `compute_flux_q`
