### ISSUE TITLE
Skip advance below leaf zones when not subcycling

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#285]
If subcycling is disabled in the AMR, then there is no need to do coarse level advances below "leaf" zones, as we do not need to interpolate in time between time level n and n+1 on the coarse grid.

This could be done also in AMReX, perhaps with the addition of an argument to MFIter that knows to skip grids if they are entirely covered by a fine grid. I believe similar functionality may exist already, or be in the works, because of the Flash efforts, I have to check.

**Comment by zingale** [comment]
we don't anticipate doing this.
