### ISSUE TITLE
MOL integration only needs 1 ghost cell (at most) for source terms

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#286]
There is no need for NUM_GROW ghost cells for MOL integration, since we don't do characteristic tracing.  The 4th order will need a single ghost cell (to allow for computation of the laplacian of the source), but the other MOL will not need any source ghost cells.

A potential exception is for certain boundary conditions, but I don't think we have a way of dealing with this right now anyway.

**Comment by maxpkatz** [comment]
Could having NUM_GROW = 1 for MOL work?

**Comment by zingale** [comment]
no, since we need NUM_GROW to be 4 for the reconstruction of the space.  But we can just but a check in there or a `do_ctu ? NUM_GROW : 1` :)
