### ISSUE TITLE
not safe to use tiling in MHD 

### ISSUE THREAD

**Issue by guadabsb15** [AMReX-Astro/Castro#289]
The MHD solver has problems when tiling. The problem shows for instance when running pure hydro Sod problem in x, y and z directions. There were discrepancies between the output for x and y(also z) when tiling. After omitting  tiling, discrepancies disappear giving the expected output

**Comment by zingale** [comment]
I think we should close this -- we are not going to necessarily fix this, so MHD will remain tileless for the near future.
