### ISSUE TITLE
add ability to print warnings from GPUs

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#2916]
Currently we disable a lot of printing of warnings from GPUs for performance reasons (just look for `#ifndef AMREX_USE_GPU`).

For debugging, it would be nice to be able to see these.  We can do the prints using `AMREX_DEVICE_PRINTF`.

We should add a build option that enables support for these warnings from GPU builds.  It should be off by default so we don't need to worry about performance, but we can enable it when we run into errors.

**Comment by yut23** [comment]
Here's a nice article that discusses how device printf can impact performance: https://developer.nvidia.com/blog/asynchronous-error-reporting-when-printf-just-wont-do/

**Comment by zingale** [comment]
this is implemented in #2923
