### ISSUE TITLE
Fortran interface adjustment for GPUs

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#296]
The (lo, hi) that the Fortran function is operating over should always be the first two arguments to the function.

**Comment by guadabsb15** [comment]
In order to make that change in the Derive_nd subroutines, there has to be some changes done in the AMReX side

**Comment by maxpkatz** [comment]
Yeah... that's special. I'm handling the launching of that kernel in AMReX separately, and it's a little messy because any change to this could break other AMReX codes. Let's leave it alone for now.
