### ISSUE TITLE
Fortran routines should only operate over (lo, hi)

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#297]
All hydro routines that operate over a region should operate over a box that is passed in to the routine. They should not do something like accept (lo, hi) from the tilebox and then proceed to loop over (lo-3, hi+3). If that is needed, pass in two additional arrays giving the bounds of the actual box to compute over, even if this means doing some unneeded calculations on the box corners or edges.

**Comment by zingale** [comment]
let's start by identifying the bad routines here:

**Comment by zingale** [comment]
>  If that is needed, pass in two additional arrays giving the bounds of the actual box to compute over, even if this means doing some unneeded calculations on the box corners or edges.

is there an example of this?

**Comment by zingale** [comment]
also, is it bad to have if-logic that basically does no-ops for some indices?

**Comment by maxpkatz** [comment]
> also, is it bad to have if-logic that basically does no-ops for some indices?

It is not bad. Preferable if you can express it as a loop that just does some redundant calculations on those indices, but if branching is necessary or not easy to remove, keep it.

**Comment by zingale** [comment]
okay fine.  I am worried about the cases where data might not be defined.

**Comment by maxpkatz** [comment]
> > If that is needed, pass in two additional arrays giving the bounds of the actual box to compute over, even if this means doing some unneeded calculations on the box corners or edges.

> is there an example of this?

https://github.com/AMReX-Astro/StarLord/blob/master/Source/ppm.F90

**Comment by zingale** [comment]
good, that was the main one I was worried about

**Comment by zingale** [comment]
the difficulty with the ppm stuff is that Castro operates on slabs...

**Comment by zingale** [comment]
routines that need updating in `hydro/`:

  *  `advection_util_nd.F90`:
    * `enforce_minimum_density` : it looks like there could be a race condition here, since we update `uout`, but at the same time we are looking at neighboring `uout` to find a reasonable density.
    * `limit_hydro_fluxes_on_small_dens` :  this does extra work in the nodal direction
    * `shock` : it looks like we could just change the bounds that we pass in here
    * `normalize_species_fluxes` : this does extra work in the nodal direction
    * `divu` : it looks like we could just pass in different bounds

**Comment by zingale** [comment]
for flattening, one idea is to compute the flattening in `ctoprim` and store it in `q_aux`
