### ISSUE TITLE
Avoid passing sliced arrays in Fortran

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#299]
Fortran array slicing (e.g. passing q(:,:,k3d,:) as a subroutine argument) should not be done. Where this occurs, pass the entire array instead.

**Comment by zingale** [comment]
we need to change the routines that call 
  * `ppm_reconstruct`
  * `ppm_int_profile`
  * `multid_slope`

for the 4th order stuff, we need to change the calls to 
  * `states`

Those seem to be the main issues in `hydro/`

**Comment by zingale** [comment]
I'll work on this on the `hydro-cleaning` branch, and try to finish it in the next few days.

**Comment by zingale** [comment]
`compute_hybrid_flux`
`compute_flux_q`

also need to be updated
