### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by patcpayne** [AMReX-Astro/Castro#319]
I have been working on determining the level of coverage the current test suite has on all of the parameters that are available in Castro. Currently, I have produced two lists of parameters: one that includes problem specific parameters and one that excludes problem specific parameters. These are lists of all of the parameters that aren't changed from their default values in at least one of the tests in the suite. I have attached the two lists here, these reports were run with the most recent execution of the castro-gfortran test suite on 2018-04-17. 

Out of the parameters that aren't being covered, which are important enough that we should develop tests for them?

[Coverage-NoSpecific.txt](https://github.com/AMReX-Astro/Castro/files/1925425/Coverage-NoSpecific.txt)
[Coverage.txt](https://github.com/AMReX-Astro/Castro/files/1925426/Coverage.txt)

**Comment by zingale** [comment]
parameters I think we should definitely cover:

```
castro.state_nghost
castro.update_sources_after_reflux
castro.use_cutom_knapsack_weights
castro.fourth_order
castro.limit_fluxes_on_small_dens
castro.sponge_implicit
castro.grav_source_type
gravity.use_mlmg_solver
diffusion.use_mlmg_solver
castro.rotation_include_centrifugal
```

**Comment by zingale** [comment]
The castro test suite will now output coverage nightly.
