### ISSUE TITLE
make mlmg the default

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#320]
Can we switch the multigrid to mlmg for both gravity and diffusion by default?

Is there any reason not to?

Related, can we rip out the old stuff?

**Comment by maxpkatz** [comment]
Do we have a recent test suite run demonstrating the diffs?

**Comment by maxpkatz** [comment]
@WeiqunZhang are all geometries in 2D and 3D supported now by MLMG?

**Comment by zingale** [comment]
let me see if I can generate one

I did it for the diffusion, and the differences were minimal.

**Comment by WeiqunZhang** [comment]
Yes, all geometries supported by AMReX (i.e., Cartesian, 1d spherical and 2d cylindrical) are supported by MLMG.

**Comment by maxpkatz** [comment]
I have no objection to switching to MLMG and ripping out the old stuff if the diffs are negligible.

**Comment by zingale** [comment]
diffusion_test now does axisymmetric, and the new solver seems to agree with the old one (and the analytic solution)

So still not sure what's up with the convective_flame.  My new guess is that perhaps they bring things to the edges differently, and it is the `diffuse_cutoff_density` that is treated different.

**Comment by zingale** [comment]
Here's the difference in the density state using the default `inputs.2d.testsuite`

![diffs_density](https://user-images.githubusercontent.com/7817509/39337704-5daf619a-498c-11e8-9dfa-d413b2d462cb.png)

**Comment by zingale** [comment]
those lines are on grid boundaries.

**Comment by zingale** [comment]
and here it is if I don't use the diffusion cutoff, `castro.diffuse_cutoff_density`.

![diffs_density_nocutoff](https://user-images.githubusercontent.com/7817509/39337770-c63d46aa-498c-11e8-82de-227bad14f253.png)

**Comment by zingale** [comment]
this is a log scale, so clearly the agreement is much better without the diffusion cutoff.  Does the new method bring the conductivity to the interfaces differently than the only scheme?  In particular, what happens if the conductivity is zero?

@WeiqunZhang ^

**Comment by WeiqunZhang** [comment]
It shouldn't matter if the conductivity is zero.  I suspect it has something to do with metric terms.  Could you try to do `cc(i,j) = cc(i,j) * (1.d0/r)` in ca_unweight_cc ?

**Comment by zingale** [comment]
instead of 
```
cc(i,j) = cc(i,j) / r
```
?

**Comment by WeiqunZhang** [comment]
Yes

**Comment by zingale** [comment]
doesn't make much of a difference.  The largest error in the diffusion term is now at the very top of the atmosphere where the density falls off.  I think that things are probably okay.

**Comment by WeiqunZhang** [comment]
I guess one possibility is rounoff errors cause one slight above and the other slightly below the cutoff.  Then they start to diverge.

**Comment by zingale** [comment]
I've investigated this further.  It turns out that the old solver does not work with multilevel axisymmetric problems.  If you run the `diffusion_test` problem, you get temperatures up to 1.e100 generated.  Things get really bad.

The new MLMG solver works great, and covergeces second order even with a jump in refinement.  Here's some convergence:

```
# base resolution     L-inf error
64                  0.0003707056645
128                 9.414571162e-05
256                 2.437072009e-05
```

In each, there is a 2x jump in refinement accounting for about 4% of the grid.

I think this shows we really need to make the new solvers the default.  I'll do a PR for this.

**Comment by zingale** [comment]
this has been merged
