### ISSUE TITLE
Double Mach-Reflection Test IC's?

### ISSUE THREAD

**Issue by sireeveslbl** [AMReX-Astro/Castro#327]
Has anyone done the Double Mach-Reflection using Castro? I'd like to see if there is a probin file for it.

**Comment by maxpkatz** [comment]
I don't believe there is one. Would you like to write the test yourself and submit a PR, or have us do it?

**Comment by zingale** [comment]
This setup is described here:

http://seesar.lbl.gov/anag/publications/colella/A3_1984.pdf

**Comment by sireeveslbl** [comment]
I have the IC's but now I need to implement the special BCs. Is there a good way to get information on the current sim time and the ICs? The top boundary follows the analytic motion of the initial shock profile, and the left BC requires the IC at every step.

**Comment by zingale** [comment]
`time` is one of the arguments to `ca_hypfill`, so you have it there already.

As for the initial conditions, you should put that in a module (like `probdata_module`).  Fill that in `probinit()` and then access it in `ca_hypfill`

**Comment by maxpkatz** [comment]
Sedov used to have an example of how to do this:

https://github.com/AMReX-Astro/Castro/blob/b620efbee69c51597bcb7708ab137f0e8de61091/Exec/hydro_tests/Sedov/bc_fill_3d.F90

**Comment by sireeveslbl** [comment]
Thanks!

**Comment by zingale** [comment]
these have been implemented
