### ISSUE TITLE
standardize includes

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#331]
sometimes we include Castro.H as:

```
#include "Castro.H"
```
and others as
```
#include <Castro.H>
```
we should be consistent

**Comment by zingale** [comment]
I don't remember why this came up -- but I don't think it is required anymore for our preprocessing.

**Comment by zingale** [comment]
do we want to do something about this? or should we close this issue?

**Comment by maxpkatz** [comment]
This came up because of the GPU script I think, which at least for now we're continuing to rely on, so we should probably still do it.

**Comment by zingale** [comment]
but which one should we do?  "blah.H" or <blah.H>?

**Comment by zingale** [comment]
This doesn't seem necessary anymore.  Usually, `""` will make the compiler search the header in the local directory first, and then places like `/usr/include`.  `<>` will only search the system standard places like `/usr/include`.  

In the AMReX build system, we add `-I. -Imorepaths`.  So it always search `.` first and then other places specified in `-I`, and then the system ones.  So the distinction doesn't matter.

For GPU stuff, we have:
```
ifeq ($(USE_GPU_PRAGMA),TRUE)
  includes    = -I$(srcTempDir) -I. $(addprefix -I, $(INCLUDE_LOCATIONS))
else
  includes    = -I. $(addprefix -I, $(INCLUDE_LOCATIONS))
endif
```
so it will always look in the `s/` directory first.

The result is that the distinction doesn't matter for us.

**Comment by maxpkatz** [comment]
Update: we now believe the distinction does matter, because we have some cases where we want to override a given header with a problem-specific implementation of that header. In that case, we need to use `<>`, because the behavior of `""` that looks first in the same directory as the source file is exactly the opposite of what we want.
