### ISSUE TITLE
CFL failure issues during retries

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#334]
In order to use retries, you have to set castro.hard_cfl_limit = 0. This allows you to not abort when a CFL violation is detected before the hydro; the hydro step is skipped, and we retry with smaller timesteps.

If a CFL violation still occurs during one of the retries, this same strategy causes problems, because we haven't yet implemented recursive subcycling (#179). It will basically lead to nonsense evolution. So we can either (a) crash at this point or (b) allow the step to be finished, potentially with unstable results.

**Comment by maxpkatz** [comment]
I vote for option (a) and will do this unless anyone objects.

**Comment by zingale** [comment]
I also vote for option (a)

**Comment by maxpkatz** [comment]
When we're using retries, we have agreed that we should always ignore castro.hard_cfl_limit and just jump directly into a retry if a CFL violation is detected (this is the whole point of the retries, so making the user select a second option to get retries to work doesn't make sense). We haven't actually done this yet, but I will do it now.

As a result, we can reinterpret the hard_cfl_limit parameter to apply during retries, so that the user can allow the unstable evolution if they really want, and I'll change the code so that you actually take the full timestep in this case.

**Comment by zingale** [comment]
that's fine with me
