### ISSUE TITLE
Build Castro without needing F_BaseLib

### ISSUE THREAD

**Issue by asalmgren** [AMReX-Astro/Castro#337]
We want to build Castro without needing F_BaseLib.  The latest commits have done that with the exception of a few lines which needs a few changes in AMReX.   Now we need to use a new version of Microphysics as well which will need to be merged.
https://github.com/AMReX-Astro/Castro/issues

**Comment by zingale** [comment]
is this done now?

**Comment by WeiqunZhang** [comment]
Yes, we should.  I will do it.  We also need to make sure regression test script works without F_BaseLib.  Michele wrote fcompare in C++ in `amrex/Tools/Postprocessing/C_Src/`.  We need to switch to using that at some point, but we still need to test it.

**Comment by zingale** [comment]
I can change the test script to use the C++ fcompare for AMReX runs and the old F90 fcompare for FBoxLib runs.

**Comment by zingale** [comment]
but we would still need those routines around for the visualization of the test suite stuff and the runtime analysis.  That would be a more time-consuming change.

**Comment by WeiqunZhang** [comment]
I will leave those there.

**Comment by zingale** [comment]
that means that F_Baselib and F_mk will still need to be part of AMReX then

**Comment by WeiqunZhang** [comment]
That means there is nothing we can remove right now without breaking the test itself.

**Comment by maxpkatz** [comment]
Well, then we need to accelerate the testing of the C++ fcompare.

**Comment by zingale** [comment]
we also need to translate the analysis routines to C++, or else we could rely on having them installed systemwide

**Comment by WeiqunZhang** [comment]
For their Fortran BoxLib based fluct hydro code, Andy uses AMReX for regression testing with FBoxLib as external source.

**Comment by zingale** [comment]
testing FBoxLib codes is easy -- you don't need AMReX at all.  It's the other way around that's a problem, and AMReX code will still need FBoxLib for testing.

**Comment by zingale** [comment]
I can confirm that if I delete `F_Baselib` in AMReX the code compiles (as of 9d7f46c78084292a682d695cbca0bc97bd8d14ec)
