### ISSUE TITLE
remove source terms for species

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#350]
In general, we don't need to have the ability to have source terms for the species.  We can make it a compile-time option, off by default, and this will save a lot of memory, and work (tracing).  This can be part of #256

**Comment by maxpkatz** [comment]
In theory we could do the same thing with other source terms (density, temperature).

**Comment by zingale** [comment]
true, but I would like to keep the source array contiguous.  If I move "shock" to be before the species stuff, then I can just lop them off and save a lot of space.

Then I can define a `NSRC` and `NQSRC` to dimension these

**Comment by zingale** [comment]
although, I suppose this is what indirect indexing is for...

**Comment by zingale** [comment]
actually, maybe the thing to do is to indicate in `_variables` if it should be in the source array

**Comment by zingale** [comment]
for the old SDC method, we need to continue to have sources for the species

**Comment by zingale** [comment]
the current version of this is on `species_sources`

**Comment by zingale** [comment]
it might be easier to just start with the primitive variable sources, and not worry about the conservative state sources.

For the primitive sources, we need to

- [ ] define a compile-time parameter PRIM_SPECIES_HAVE_SOURCES that is used to determine whether the primitive variable state species have sources.  We will default it to FALSE until SDC is set to TRUE.
- [ ] make NQSRC a new parameter that is determined at compile time.  This will be used to dimension the primitive source arrays
- [ ] change srctoprim to skip the species sources if we are not using them
- [ ] change the dimensions of Ip_src and Im_src and have the bounds of the loop that fills them be over NQSRC
- [ ] change the trace routines to only add the species sources if they exist

**Comment by zingale** [comment]
doing this on `no_species_sources`

**Comment by zingale** [comment]
With #519, this is essentially implemented.
