### ISSUE TITLE
Force new dt after regrid

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#356]
Amr has a parameter compute_new_dt_on_regrid which is disabled by default. But we want this option to be on for most of the problems that are of interest to Castro, which can evolve rapidly and for which updating the timestep after generating new regrid data is probably wise. So we should force this option to be on by default in Castro, assuming that we can find a way to still allow the user to disable it if they really want to.

**Comment by zingale** [comment]
we should just turn this on by default.
