### ISSUE TITLE
Retry scheme incorrect if we retry in the middle of the subcycles

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#358]
When we retry, we copy the saved old-time data back to the state, but we continue evolving from the last completed subcycle -- this is contradictory. We either need to update the saved old-time state after each successful subcycle, or we need to restart from the beginning of the main step on every retry.

**Comment by maxpkatz** [comment]
The first option is suboptimal because the point of the current scheme is to make it look like we only took a single step after all the subcycles are done; this will destroy that goal. The second option means some wasted subcycles but is likely the safest route.

**Comment by zingale** [comment]
I like the second option.  I don't think the waste is that big of a deal
