### ISSUE TITLE
radiation solver should not have specific problems hardcoded in

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#36]
There are multiple instances of `do_rad_sphere` in the radiation solver.  These should be removed and instead located in a problem-specific routine

**Comment by zingale** [comment]
this has been moved from `LHH.H` into `RadTests.H`, to just separate these to allow for progress on issue #52

**Comment by zingale** [comment]
it looks like what remains here is `do_thermal_wave_cgs` which is used to compute the analytic solution (maybe this can be done via a derived variable in the problem?) and `do_rad_sphere` which is used to initialize the groups.

**Comment by maxpkatz** [comment]
This is now resolved.
