### ISSUE TITLE
RadThermalWave should not override Tagging_nd.f90

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#362]
problem_tagging_nd.f90 exists for this purpose, the custom tagging should be moved to that routine.

**Comment by zingale** [comment]
it's not clear why this version is even needed.  It looks like it doesn't do anything different than the default temp tagging

**Comment by maxpkatz** [comment]
Well, in 1D and 2D it is different because it is using tempgrad for a relative measure, not an absolute measure (this functionality can now be replaced with tempgrad_rel). In 3D, it is different because it's also only applying the tagging if T > temperr, which is not functionality that currently exists, and it would require a custom tagging routine.

**Comment by maxpkatz** [comment]
Also, it's doing the relative gradient measure by computing the root mean square over all dimensions rather than by doing it independently in each dimension -- we should think about whether we want to do tempgrad_rel this way too.

**Comment by maxpkatz** [comment]
The functionality to only tag gradients if the field itself is above some threshold is something I had already been thinking about while working on the Detonation problem -- maybe I'll implement that.

**Comment by maxpkatz** [comment]
OK -- what I'm going to do is implement the threshold functionality, then just delete the custom tagging in RadThermalWave. I won't change how tempgrad_rel is done -- I prefer the stronger criterion that looks in all directions independently. This will change results for RadThermalWave, but I just noticed a typo in Tagging_nd.f90 anyway: `gradT = sqrt(ax**2 + ay**2 + az*82)`. Fixing that would change answers anyway.

**Comment by zingale** [comment]
oh.... I just changed this to use the relative error.  Doesn't look like the threshold was being used anyway, since I get the same answers (in 2-d).  I'll close this, since it is only a test problem anyway.
