### ISSUE TITLE
"visualization of the results" NOT O.K. as Boxlib2D,Boxlib3D in VisIt for me. Is it true for you,Sir?

### ISSUE THREAD

**Issue by xumustc** [AMReX-Astro/Castro#370]
As a dummy user,I have been confused by visualization of CASTRO.May I have the right to
clarify here?Here it is :

It takes 5 weeks to get through the first 5 pages in chapter 2.3 of CASTROUserGuide.pdf. 
The most time consume is spent on update GCC,which is required higher than 4.8.After installation of GCC-8.1.0,the  Castro2d.Linux.gnu.ex was born! The ‘Running the Code’ ran normally and quickly. The plt00000/, plt00020/, etc, were also produced.
Unfortunately,when using VisIt2.7.3(WindowsXP-version) point the head file ‘Header’ on Linux，we get the error message like:

‘VisIt was unable to open "***/Header". Each attempt to open it caused VisIt's metadata server to crash. This can occur when the file is corrupted, or when the underlying file format has changed and VisIt's readers have not been updated yet, or when the reader VisIt is using for your file format is not robust. Please check whether the file is corrupted and, if not, contact a VisIt developer.
’

Then we test the normal HyperClaw files from 
https://ccse.lbl.gov/pub/ExamplePlotFiles/HyperCLaw/
,but the similar error occurs:

VisIt was unable to open "F:\***\amrvis\HyperClaw\plt00010\Header". Each attempt to open it caused VisIt's metadata server to crash. This can occur when the file is corrupted, or when the underlying file format has changed and VisIt's readers have not been updated yet, or when the reader VisIt is using for your file format is not robust. Please check whether the file is corrupted and, if not, contact a VisIt developer.

Where
F:\***\amrvis\HyperClaw\plt00010\Header
are copied from https://ccse.lbl.gov/pub/ExamplePlotFiles/HyperCLaw/

B.T.W.:
AMRex is from
https://github.com/AMReX-Codes/amrex
CASTRO is from
https://github.com/AMReX-Astro/Castro

Is it true for your CASTRO,too,Sir?
Please help me about it.
Thank you in advance!!

**Comment by zingale** [comment]
Hi xumustcm thanks for using the code and posting an issue.  I'm sorry you had trouble building the GCC compilers, but as you've found, 4.8 is quite old, and Castro (and AMReX) use C++ 11 and 14 features.  For the visualization, I suspect that the version of VisIt you are using doesn't have the BoxLib reader compiled in.  This is a pretty old version of VisIt, so can you try installing one of the later versions?

Alternately, many of us don't use VisIt, but instead use the python library yt, which can read Castro data without difficulties.  There are a lot of examples for using yt on their website: http://yt-project.org/

**Comment by maxpkatz** [comment]
I think this is an issue specific to the Windows version of VisIt. The Linux versions usually work.

**Comment by zingale** [comment]
has this been resolved?

**Comment by xumustc** [comment]
Thank you so much,
Thank you so much,zingale and maxpkatz! 
Let me try the Linux version of VisIt 2.12 from https://wci.llnl.gov/simulation/computer-codes/visit/source.
Best Regards

**Comment by xumustc** [comment]
Thanks a lot, zingale and maxpkatz!
The pltfiles from Castro is O.K. by amrvis.
