### ISSUE TITLE
Simplify, generalize MonopoleGrav

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#378]
For WD collisions I would like to be able to evaluate the gravity cheaper and less accurately, since it is not particularly important to get the gravity right for this problem, so saving on cycles is valuable if they can be traded for cycles in the hydro and reactions. This becomes especially apparent in multi-level simulations, where doing a multigrid solve (or even interpolating from the coarse grid) is relatively expensive.

In particular I would like to be able to write a "dual monopole" gravity. In wdmerger we already have the tools set up to evaluate the center of mass, and stellar mass, of each star. Assuming spherical WDs, then, it would be a straightforward local calculation to obtain the monopole acceleration and potential from each star anywhere in the domain, and both of these could be summed.

However, monopole gravity is currently too inflexible to do something like this, given that it was written primarily assuming a spherically symmetric mass distribution centered at the origin. What needs to be done is generalize the calculation so that it uses calculations that do not make any assumptions about geometry or location on the domain. 

The first step is to replace the custom logic for the gravity with existing functionality such as volWgtSum to calculate the mass on the domain, and then instead of integrating the gravity outwards and interpolating a radial profile onto the domain, simply writing down g = -GM_enclosed / r^2 in every zone. This would significantly clean up this part of the code base. But it's not clear if this can be done without replicating much of the current functionality, since we cannot assume a homogeneous mass distribution and still be accurate inside the star.

The second step is to calculate the mass and location of each monopole, which can be done by assuming that the zones belonging to each monopole are the ones closer to its location than any other monopole. (The circularity in this logic is avoided by using the monopole's location in the last timestep as a starting guess for the integration.) Then we can simply sum over -GM/r^2 for each monopole.

**Comment by maxpkatz** [comment]
Some issues to think about:
- What is the value of the current MonopoleGrav approach, where we integrate over an arbitrary number of radial bins and do the interpolation on a zone-by-zone basis? Is this more accurate? Do we want to try and keep this functionality?
- How do we deal with GR gravity?

**Comment by zingale** [comment]
we no longer favour this approach
