### ISSUE TITLE
Segfault in makeKnapsack when using custom burn weights

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#382]
A segfault occurs in the DIM==2 wdmerger problem using the `inputs` from the `knapsack_crash` branch. If DEBUG mode is on, the code crashes in DistributionMapping::KnapSackDoIt after a few timesteps. This only occurs with a sufficiently high number of allowed levels.

**Comment by maxpkatz** [comment]
This occurs because we are calling the knapsack generator with a weights array that is all zero, and it results in a divide by zero when setting the scaling factor in the knapsack routine. The fact that it is zero is Castro's fault. We initialize the weights to zero in the new data when the simulation is initialized. Prior to the first burn, the new data gets swapped to the old data, so when we enter the old-time burn we'd have a weights array of ones, which is a valid configuration. However, for the inputs in this branch's setup, we are skipping the initial burn because the temperature is not high enough. This means that in the second timestep, the swap would leave the old data uninitialized, and this will keep being true on every second timestep until the conditions reach the threshold for burning. So ultimately we are just calling the knapsack with uninitialized data which is being set to zero (by the compiler, I guess) which results in the issue.

**Comment by maxpkatz** [comment]
Actually a more important issue is that there was a bug in how we set the weights:

weights(i,j,k) = min(ONE, dble(burn_state_out % n_rhs + 2 * burn_state_out % n_jac))

This means two things: 1) if n_rhs == 0 and n_jac == 0, which can happen for some zones if we skip the integration because they haven't reached the burn validity criterion yet; 2) since we were setting it to the _minimum_ of 1 and N, this meant the weights were always 1, which means that the custom knapsack could not have been doing anything useful. This bug was introduced in 0b2840cb6f65b58851fd5d1ff3a6ca1e956b6817 in November 2016.

**Comment by maxpkatz** [comment]
@WeiqunZhang, the issue on the AMReX side is when we generate the scale factor in makeKnapsack:

```
    Real wmax = *std::max_element(rcost.begin(), rcost.end());
    Real scale = 1.e9/wmax;
```

If the weights array is uniformly zero, this results in a divide by zero. I've fixed the Castro bug which could cause the weights array to be zero, and you may want to divide by, e.g., std;:max(wmax, 1.e-6).

**Comment by WeiqunZhang** [comment]
We knew the issue.  I thought we have fixed it.  But apparently we only
fixed it in one place.  There are two other places in DistributionMapping.
Could you make the changes?  I am on my phone.  Just search for
max_element.  We fixed by testing w==0.

**Comment by maxpkatz** [comment]
Done
