### ISSUE TITLE
Move build-created files to tmp_build_dir

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#388]
Files such as extern.F90 should be generated in tmp_build_dir, not the parent build location, in case they differ as a result of build options. This is easiest to do if we merge the change in from the amrex gpu branch that copies all files to tmp_build_dir/s/ first.

**Comment by zingale** [comment]
Related to #359

**Comment by maxpkatz** [comment]
In the original gpu branch we always used tmp_build_dir for temporary source files regardless of whether we were using CUDA, but in AMReX development this has been limited so that we only do this with tmp_build_dir if we're using CUDA, so it's not as trivial as I originally expected.

**Comment by maxpkatz** [comment]
This is done by #726
