### ISSUE TITLE
have VODE start with the last timestep

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#391]
VODE currently uses its own internal algorithm to decide on the starting timestep.  If you look at the path that VODE takes in phase space, it has lots of small steps at the start of integration.  We should be able to start with a larger step, especially for SDC in later iterations.

VODE stores this information in `RWORK(5)`, with a value of `0` indicating that it should determine the initial step size.

**Comment by dwillcox** [comment]
I'm taking a look at this, I should have a PR for you to look at sometime soon.

**Comment by dwillcox** [comment]
Yes, the alternative using VODE is to save the state data and restore it, but that's a lot of memory. There doesn't seem to be a good way to avoid saving its internal state and still start at high order since it needs to bootstrap itself up to high order when it starts from scratch.

**Comment by zingale** [comment]
okay.  Closing this then.  We can explore other integrators separately.
