### ISSUE TITLE
rewrite react_state problem

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#404]
it is currently a simple port of the Maestro version, so it really is in the F90 logic.

**Comment by zingale** [comment]
I think this issue refers to `test_react`

**Comment by dwillcox** [comment]
What needs to be rewritten and does reactions_driver_test do what you want already?

**Comment by zingale** [comment]
I don't remember what we didn't like, as this came up during the hackathon, but I think we wanted the driver all in C++ so we could make it use the GPU stuff and then call a Fortran kernel to do the burn.  So we'd want to setup a multifab in C++ with the state data.

**Comment by dwillcox** [comment]
Oh, ok, that's exactly what reactions_driver_test does.

**Comment by zingale** [comment]
okay... so maybe we can get rid of `test_react` then?

**Comment by dwillcox** [comment]
Sounds good, first I'll double check that they are setting the initial state the same way so we can expect the same results.

**Comment by zingale** [comment]
bumping this up... can we just get rid of `test_react`?  It looks like `reactions_driver_test` just does 1 step of a burn and that's it.  So that's what we want.
