### ISSUE TITLE
Hi,Friends! How to create the initial mesh for Castro?

### ISSUE THREAD

**Issue by xumustc** [AMReX-Astro/Castro#412]
Hi,Friends!
I am a green hand and wander:
How to create the initial mesh for Castro?
For example, create a spherical zone in one rectangular zone.
Is there any open-source tool?
Thanks in advance!

**Comment by xumustc** [comment]
Thank you so much,Mr Zingale!

I mean that ,if we want to simulate the underwater volcano eruption by Castro,the initial rock plasma erupted  is surrounded by sea water.
How to set the rock plasma region,for example, with one sphere of rock density and high temperature?
How to set its surrounding sea water with the left region of density~1.0 g/cm3 and normal temperature?
Best Regards

**Comment by zingale** [comment]
As long as everything is a fluid, and you have an appropriate equation of state that can describe things, then you can make the different components different compositions.  Castro usually thinks about these as being nuclei, but they can really be anything.  You will need to create a "network", even if you are not reacting.  The easiest way to do this is to set the network to `general_null`, and then create a composition file with the properties that you need for your EOS.  Take a look, for instance, at `Castro/Microphysics/networks/general_null/simple.net`
