### ISSUE TITLE
evrard_collapse experiences CUDA Error when compiled with CUDA

### ISSUE THREAD

**Issue by harpolea** [AMReX-Astro/Castro#417]
This is one of the examples in Exec/gravity_tests. I traced the error back to `ca_sumproduct` in `sum_utils.cpp/volProductSum()` when it is called by https://github.com/AMReX-Astro/Castro/blob/7e695cc2312f15eeadff9495c46025a4cec30666/Source/driver/sum_integrated_quantities.cpp#L71. If I stop `ca_sumproduct` from being offloaded to the GPU, it no longer experiences the error. 

I'm not sure if this is an error in `ca_sumproduct` itself, or in the arguments that are being passed to it (e.g. there is a Real scalar passed to it by reference which I suspect may be wrong).

**Comment by harpolea** [comment]
After some more testing it appears that phiGrav is not being initialised properly - if I run `fcompare` on subsequent runs, then there is an error in phiGrav

**Comment by zingale** [comment]
does this happen with both MonopoleGrav and PoissonGrav?

**Comment by harpolea** [comment]
Just PoissonGrav - if i run the original code with MonopoleGrav there are no errors

**Comment by maxpkatz** [comment]
I fixed an issue in sumproduct, please verify whether this resolves your issue.

**Comment by harpolea** [comment]
Yes, both monopole and Poisson work fine now - thanks!
