### ISSUE TITLE
building wdmerger on Cori (gnu compiler)

### ISSUE THREAD

**Issue by cychan-lbnl** [AMReX-Astro/Castro#419]
This is with the master branches of Castro/Microphysics/amrex, on Cori.  I tried building Castro/Exec/science/wdmerger, but get a compile error:

sum_integrated_quantities.cpp: In member function 'void Castro::sum_integrated_quantities()':
sum_integrated_quantities.cpp:60:5: error: 'get_omega_vec' was not declared in this scope
     get_omega_vec(omega, time);
     ^~~~~~~~~~~~~
sum_integrated_quantities.cpp:146:5: error: 'get_axes' was not declared in this scope
     get_axes(axis_1, axis_2, axis_3);
     ^~~~~~~~
sum_integrated_quantities.cpp:146:5: note: suggested alternative: 'rot_axis'
     get_axes(axis_1, axis_2, axis_3);
     ^~~~~~~~
     rot_axis
sum_integrated_quantities.cpp:301:5: error: 'get_star_data' was not declared in this scope
     get_star_data(com_p, com_s, vel_p, vel_s, &mass_p, &mass_s, &t_ff_p, &t_ff_s);
     ^~~~~~~~~~~~~
sum_integrated_quantities.cpp:301:5: note: suggested alternative: 'get_state_data'
     get_star_data(com_p, com_s, vel_p, vel_s, &mass_p, &mass_s, &t_ff_p, &t_ff_s);
     ^~~~~~~~~~~~~

I traced these errors to the wrong version of identically named headers being included in sum_integrated_quantities.cpp.  For example, for the directive "#include <Problem_F.H>", the preprocessor includes Castro/Source/problems/Problem_F.H rather than Castro/Exec/science/wdmerger/Problem_F.H, even though when specifying include search directories, -ICastro/Exec/science/wdmerger appears before -ICastro/Source/problems in the compile command.  I worked around this issue by deleting the header files in Castro/Source/problems that have duplicate names in Castro/Exec/science/wdmerger to force it to use the ones in the wdmerger directory.

**Comment by zingale** [comment]
I wonder if this is an issue with doing

```#include <Problem_F.H>```

vs.

```#include "Problem_F.H"```

we seem to do it differently in different places.

**Comment by cychan-lbnl** [comment]
Replacing <> with "" for Problem.H and Problem_F.H changes, but doesn't fix
the issue:

sum_integrated_quantities.cpp: In member function 'void
Castro::sum_integrated_quantities()':
sum_integrated_quantities.cpp:208:14: error: 'class Castro' has no member
named 'gwstrain'
       ca_lev.gwstrain(time, h_plus_1, h_cross_1, h_plus_2, h_cross_2,
h_plus_3, h_cross_3, local_flag);
              ^~~~~~~~


If you just run the preprocessor (cpp), you'll see that the wrong Problem.H
is being included from Castro.H, so some necessary members of class Castro
get omitted.  But the correct version of Problem.H is included directly
into the sum_integrated_quantities.cpp file.  This behavior is totally
mysterious to me.

**Comment by zingale** [comment]
what happens if you change line 376 in `Make.Castro` from
```
INCLUDE_LOCATIONS += $(Blocs)
```
to
```
INCLUDE_LOCATIONS += . $(Blocs)
```

**Comment by zingale** [comment]
also, indpendently, can you show the output of 
```
make print-INCLUDE_LOCATIONS
```

**Comment by cychan-lbnl** [comment]
Adding . to the INCLUDE_LOCATIONS in Make.Castro doesn't change anything
(and it really shouldn't since Castro/Exec/science/wdmerger/ already
appears before Castro/Source/problems/ in the existing list).  I'm starting
to wonder if this is a gcc bug.

Here's the output of make print-INCLUDE_LOCATIONS (without the change to
Make.Castro).  Again, please excuse the use of the seemingly redundant
amrex parent directory:

cchan2@cori10:/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Exec/science/wdmerger
(master) $ make print-INCLUDE_LOCATIONS
Loading
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/GNUMake/comps/gnu.mak...
Loading
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/GNUMake/sites/Make.nersc...
INCLUDE_LOCATIONS is
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/Base
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/AmrCore
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/Amr
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/Boundary
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/LinearSolvers/C_CellMG
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/LinearSolvers/MLMG
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/util
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/util/LINPACK
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/util/BLAS
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration/VODE
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration/VODE/vode_source/
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration/BS
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/rates
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/screening
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/neutrinos
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Exec/science/wdmerger/
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/driver
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/driver/param_includes
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/hydro
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/problems
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/sources
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/constants
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Util/model_parser
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/gravity
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/reactions
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/rotation
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Microphysics/EOS
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/EOS/helmholtz
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Microphysics/networks
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/networks/aprox13
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/EOS
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/networks
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/C_scripts

**Comment by zingale** [comment]
This is starting to seem like a bug on Cori then.

**Comment by zingale** [comment]
is this still an issue?

**Comment by cychan-lbnl** [comment]
Yes, I've been able to build and run with the Intel compiler (PrgEnv-intel/6.0.4, intel/18.0.2.199), but not with (PrgEnv-gnu/6.0.4, gcc/7.3.0) due to the above issue.  I'm on the development branches of Castro/AMReX/Microphysics.

**Comment by maxpkatz** [comment]
I don't reproduce this issue on Cori with the current code or with 18.10. If this is still an issue for you, please post the exact make statement you're using, and the output of `module list` so that I can to reproduce it as closely as possible.

**Comment by cychan-lbnl** [comment]
Hi Max,

I'm on commits:

Castro: 667c955270afd69b8254018a36f3ae531b635278
amrex: 565a8449d82f41aa225d65e15f4cfc8020c3f0a9
Microphysics: 719edc0ca3d050947697f54211c4e4c79b93ebe9

Here's my module list:

cchan2@cori07:/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Exec/science/wdmerger
(development) $ module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.6                                  9) darshan/3.1.4
                                17) xpmem/2.2.15-6.0.7.1_5.10__g7549d06.ari
  2) nsg/1.2.0                                        10)
python/2.7-anaconda-4.4                          18)
job/2.2.3-6.0.7.0_44.1__g6c4e934.ari
  3) gcc/7.3.0                                        11)
cray-libsci/18.07.1                              19)
dvs/2.7_2.2.116-6.0.7.1_8.11__g0dac9eb
  4) craype-haswell                                   12)
udreg/2.3.2-6.0.7.0_33.18__g5196236.ari          20)
alps/6.6.43-6.0.7.0_26.4__ga796da3.ari
  5) craype-network-aries                             13)
ugni/6.0.14.0-6.0.7.0_23.1__gea11d3d.ari         21)
rca/2.2.18-6.0.7.0_33.3__g2aa4f39.ari
  6) craype/2.5.15                                    14) pmi/5.0.14
                               22) atp/2.1.3
  7) cray-mpich/7.7.3                                 15)
dmapp/7.1.1-6.0.7.0_34.3__g5a674e0.ari           23) PrgEnv-gnu/6.0.4
  8) altd/2.0                                         16)
gni-headers/5.0.12.0-6.0.7.0_24.1__g3b1768f.ari

And here's the make output:

cchan2@cori07:/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Exec/science/wdmerger
(development) $ make
Loading
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/GNUMake/comps/gnu.mak...
Loading
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/GNUMake/sites/Make.nersc...
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/C_scripts/describe_sources.py
\
          --git_names "Castro AMReX Microphysics" \
          --git_dirs "/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro
/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex
/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics"

source git hashes:
  Castro              : 19.02-50-g667c9552
  AMReX               : 19.02-159-g565a8449d
  Microphysics        : 19.02-dirty


Compiling sum_integrated_quantities.cpp ...
CC  -g -O3  -fopenmp -DNDEBUG -DBL_USE_MPI -DAMREX_USE_MPI -DBL_USE_OMP
-DAMREX_USE_OMP -DAMREX_GIT_VERSION=\"19.02-159-g565a8449d82f\"
-DBL_GCC_VERSION=7.3.0 -DBL_GCC_MAJOR_VERSION=7 -DBL_GCC_MINOR_VERSION=3
-DAMREX_LAUNCH="" -DAMREX_DEVICE="" -DAMREX_CUDA_FORT_GLOBAL=""
-DAMREX_CUDA_FORT_DEVICE="" -DAMREX_CUDA_FORT_HOST="" -DBL_SPACEDIM=3
-DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE
-DBL_Linux -DAMREX_Linux -DAMREX_DIMENSION_AGNOSTIC -DCRSEGRNDOMP -DSPONGE
-DGRAVITY -DSELF_GRAVITY -DREACTIONS -DHYBRID_MOMENTUM -DROTATION
-DCASTRO_MLMG -DINTEGRATOR=0 -I.
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/Base
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/AmrCore
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/Amr
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/Boundary
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/LinearSolvers/C_CellMG
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Src/LinearSolvers/MLMG
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/util
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/util/LINPACK
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/util/BLAS
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration/VODE
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration/VODE/vode_source/
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration/BS
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/integration
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/rates
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/screening
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/neutrinos
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Exec/science/wdmerger/
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/driver
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/driver/param_includes
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/hydro
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/problems
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/sources
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/constants
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Util/model_parser
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/gravity
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/reactions
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Source/rotation
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Microphysics/EOS
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/EOS/helmholtz
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Castro/Microphysics/networks
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/networks/aprox13
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/EOS
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/Microphysics/networks
-I/global/cscratch1/sd/cchan2/projects/lbl/amrex/amrex/Tools/C_scripts -c
sum_integrated_quantities.cpp -o
tmp_build_dir/o/3d.gnu.haswell.MPI.OMP.EXE/sum_integrated_quantities.o
sum_integrated_quantities.cpp: In member function 'void
Castro::sum_integrated_quantities()':
sum_integrated_quantities.cpp:60:5: error: 'get_omega_vec' was not declared
in this scope
     get_omega_vec(omega, time);
     ^~~~~~~~~~~~~
sum_integrated_quantities.cpp:64:33: error: 'mdot_p' was not declared in
this scope
     Real mdot = 0.5 * (std::abs(mdot_p) + std::abs(mdot_s));
                                 ^~~~~~
sum_integrated_quantities.cpp:64:33: note: suggested alternative: 'mdot'
     Real mdot = 0.5 * (std::abs(mdot_p) + std::abs(mdot_s));
                                 ^~~~~~
                                 mdot
sum_integrated_quantities.cpp:64:52: error: 'mdot_s' was not declared in
this scope
     Real mdot = 0.5 * (std::abs(mdot_p) + std::abs(mdot_s));
                                                    ^~~~~~
sum_integrated_quantities.cpp:64:52: note: suggested alternative: 'mdot'
     Real mdot = 0.5 * (std::abs(mdot_p) + std::abs(mdot_s));
                                                    ^~~~~~
                                                    mdot
sum_integrated_quantities.cpp:146:5: error: 'get_axes' was not declared in
this scope
     get_axes(axis_1, axis_2, axis_3);
     ^~~~~~~~
sum_integrated_quantities.cpp:146:5: note: suggested alternative: 'rot_axis'
     get_axes(axis_1, axis_2, axis_3);
     ^~~~~~~~
     rot_axis
sum_integrated_quantities.cpp:208:14: error: 'class Castro' has no member
named 'gwstrain'
       ca_lev.gwstrain(time, h_plus_1, h_cross_1, h_plus_2, h_cross_2,
h_plus_3, h_cross_3, local_flag);
              ^~~~~~~~
sum_integrated_quantities.cpp:301:5: error: 'get_star_data' was not
declared in this scope
     get_star_data(com_p, com_s, vel_p, vel_s, &mass_p, &mass_s, &t_ff_p,
&t_ff_s);
     ^~~~~~~~~~~~~
sum_integrated_quantities.cpp:301:5: note: suggested alternative:
'get_state_data'
     get_star_data(com_p, com_s, vel_p, vel_s, &mass_p, &mass_s, &t_ff_p,
&t_ff_s);
     ^~~~~~~~~~~~~
     get_state_data
sum_integrated_quantities.cpp:337:20: error: 'norm' was not declared in
this scope
       separation = norm(wd_dist);
                    ^~~~
sum_integrated_quantities.cpp:337:20: note: suggested alternative: 'fork'
       separation = norm(wd_dist);
                    ^~~~
                    fork
sum_integrated_quantities.cpp:379:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:510:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:568:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:630:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:687:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:746:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:820:75: error: 'rad_p' was not declared in
this scope
         log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rad_p[i];

 ^~~~~
sum_integrated_quantities.cpp:820:75: note: suggested alternative: 'rand_r'
         log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rad_p[i];

 ^~~~~

 rand_r
sum_integrated_quantities.cpp:840:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:914:75: error: 'rad_s' was not declared in
this scope
         log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rad_s[i];

 ^~~~~
sum_integrated_quantities.cpp:914:75: note: suggested alternative: 'radius'
         log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rad_s[i];

 ^~~~~

 radius
sum_integrated_quantities.cpp:934:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:970:71: error: 'T_curr_max' was not declared
in this scope
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
T_curr_max;

 ^~~~~~~~~~
sum_integrated_quantities.cpp:971:71: error: 'rho_curr_max' was not
declared in this scope
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rho_curr_max;

 ^~~~~~~~~~~~
sum_integrated_quantities.cpp:971:71: note: suggested alternative:
'react_T_max'
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rho_curr_max;

 ^~~~~~~~~~~~

 react_T_max
sum_integrated_quantities.cpp:972:71: error: 'ts_te_curr_max' was not
declared in this scope
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
ts_te_curr_max;

 ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:973:71: error: 'T_global_max' was not
declared in this scope
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
T_global_max;

 ^~~~~~~~~~~~
sum_integrated_quantities.cpp:974:71: error: 'rho_global_max' was not
declared in this scope
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
rho_global_max;

 ^~~~~~~~~~~~~~
sum_integrated_quantities.cpp:975:71: error: 'ts_te_global_max' was not
declared in this scope
     log << std::setw(datwidth) << std::setprecision(dataprecision) <<
ts_te_global_max;

 ^~~~~~~~~~~~~~~~
sum_integrated_quantities.cpp:995:7: error: 'writeGitHashes' was not
declared in this scope
       writeGitHashes(log);
       ^~~~~~~~~~~~~~

**Comment by maxpkatz** [comment]
Cy, I still don't reproduce it using that module set on those commits. However I do see

`Microphysics        : 19.02-dirty`

in the build. What local change did you make to Microphysics? Can you stash it and `make realclean` and try again?

**Comment by cychan-lbnl** [comment]
Hi Max, I did a clean build from scratch (all master branches), and this time it works.  Thanks again for your help!
