### ISSUE TITLE
running wdmerger on Cori

### ISSUE THREAD

**Issue by cychan-lbnl** [AMReX-Astro/Castro#420]
After doing the workaround described in Issue #419 (building wdmerger on Cori), the code compiles, but does not run successfully when using the command given in Castro/Docs/ManagingJobs/scaling/wdmerger/cori_201710/cori-nodes_16.knl.MPI.OMP.slurm.  It gives an error: 

At line 57 of file wdmerger_util.f90 (unit = 9, file = 'probin_test_wdmerger_3D')
Fortran runtime error: Cannot match namelist object name fill_ambient_bc

I'm not familiar with Fortran namelists, so I don't know how to debug this issue.  Any suggestions would be most appreciated!

**Comment by zingale** [comment]
I think that runtime parameter was removed a while back, so simply delete that line from the probin file.

**Comment by cychan-lbnl** [comment]
Worked, thanks!
