### ISSUE TITLE
Rad2TShock has NaNs in initial reset energy

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#423]
See the output from the test suite:

http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2018-10-15/rad-2Tshock-3d.run.out

when you run `Rad2TShock` in 3d with `inputs.M2.test`, you get NaNs in the initial `reset_internal_energy`, before any hydro takes place:

```
 >>> Warning: Castro_util.F90::reset_internal_energy            -1          -1          -1
 >>> ... resetting neg. e from EOS using small_temp
 >>> ... from                        NaN  to                        NaN
     
    
 >>> Warning: Castro_util.F90::reset_internal_energy             0          -1          -1
 >>> ... resetting neg. e from EOS using small_temp
 >>> ... from                        NaN  to                        NaN
     
    
 >>> Warning: Castro_util.F90::reset_internal_energy             1          -1          -1
 >>> ... resetting neg. e from EOS using small_temp
 >>> ... from                        NaN  to                        NaN
     
 ...
```

**Comment by zingale** [comment]
these NaNs entered in the 2 days period from:

2018-06-29 (Castro hash: 08e2700aeda951324e9df9009a6b242359fe2c8e)  -- no NaNs

2018--07-01 (Castro hash: f7ab2d932805e90f9ca6fc376382f3e1eb2b0136) -- NaNs

should be easy to `git bisect`

**Comment by zingale** [comment]
this is when we made the state vector size known at compile time and required that `NGROUPS` be set as a make parameter.

**Comment by zingale** [comment]
this problem still exists, but I can only trigger it in Debug mode.

**Comment by maxpkatz** [comment]
In reset_internal_energy, we do the reset on the growntilebox, where the number of ghost zones is set by querying the state data that we're operating on. However, computeTemp that is calling it (which in turn is called by clean_state) has `ng` passed to it, and in the call to `expand_state` where this is originating from, we're passing `ng == 0`:

```

  if (iclean == 0) {
    clean_state(iclean, 0);
  } else if (iclean == 1) {
    clean_state(iclean, 0);
  } else if (iclean == 2) {
    clean_state(0, 0);
    clean_state(1, 0);
  }
```
So this is an inconsistency to potentially be fixed. I'm not sure yet why reset_internal_energy is getting bad data though, I would expect S_old to have meaningful data on its ghost zones at this point.

**Comment by maxpkatz** [comment]
The zeroed data is intentional and coming from `initialize_do_advance`:
```
#ifdef RADIATION
    // make sure these are filled to avoid check/plot file errors:                                                              
    if (do_radiation) {
      get_old_data(Rad_Type).setBndry(0.0);
      get_new_data(Rad_Type).setBndry(0.0);
    }
    else {
      get_old_data(Rad_Type).setVal(0.0);
      get_new_data(Rad_Type).setVal(0.0);
    }
    get_old_data(State_Type).setBndry(0.0);
    get_new_data(State_Type).setBndry(0.0);
#endif
```
So I will submit a PR to make reset_internal_energy only work on the valid domain, since that's all we need here anyway.

**Comment by zingale** [comment]
this issue is fixed now, with the above merge
