### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#425]
We should be able to setup a CI system to run on PRs by having groot monitor github for PRs and then launching the tests there and updating the PR.  Maybe this means having travis run locally?

**Comment by dwillcox** [comment]
This looks helpful -- https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e

**Comment by zingale** [comment]
The testsuite can now run without web output (just set the webTopDir to "").  The return code for the suite is just the number of failures, so it returns 0 if everything passes (and travis should recognize that).

What remains is that we need to understand how to get both AMReX and Microphysics into the travis instance.  I.e., can we do a `git clone` from within there?  We need to read on this.

We can then do a few short tests on all PRs, assuming that AMReX and Microphysics are on `development`.  We need to tell the suite not to do an update on Castro, since it will be on the hash for the PR already in travis (I think).

**Comment by zingale** [comment]
We also need to git clone regression_testing

**Comment by harpolea** [comment]
For storing benchmarks, we could use [Zenodo](https://zenodo.org/) - this allows up to 50GB of storage per project and data can be uploaded using the python `requests` package (via [its REST API](http://developers.zenodo.org/#rest-api)). 

Some care will be needed here with respect to authentication as it would require an access token - I think you can keep this secret by setting it as an environment variable in the repo's settings in travis. There's some more info [here](https://docs.travis-ci.com/user/best-practices-security/#Steps-Travis-CI-takes-to-secure-your-data) which might be useful.

**Comment by zingale** [comment]
we should do something here for #665

**Comment by zingale** [comment]
we've now done some of this -- we have Sedov run via the CI.  We can add more problems as desired.
