### ISSUE TITLE
Hi!Sharing some experiences about build gcc and VisIt for Castro on Linux

### ISSUE THREAD

**Issue by xumustc** [AMReX-Astro/Castro#426]
Hi!Sharing some experiences about build gcc and VisIt for Castro on Linux

Castro requires gcc-4.8 +,and so gcc-4.8.3 is recommended by my humble experiences.When configuring,i.e., ‘configure --…’,some options are recommended such as:
1.	‘--disable-multilib’ for some system where the gnu/stubs-32.h is missing.
2.	‘--with-system-zlib’ when you are facing such error report as ‘configure -stage1-zlib’.
If such error reported as “ ‘GATHER_STATISTICS’ must be defined”, you can try type such command in terminal as ‘unset LIBRARY_PATH CPATH C_INCLUDE_PATH PKG_CONFIG_PATH CPLUS_INCLUDE_PATH INCLUDE DYLD_LIBRARY_PATH’.

Before building VisIt 2.13.2, you had better check this:
“nm libstdc++.so.6 | grep ‘GLIBCXX_3.4.14’ ” for your compiler’s lib,such as gcc’s lib64/libstdc++.so.6.
If your rebuild VisIt 2.13.2 again due to last failure, you had better delete all the unzipped directories, otherwise such error maybe appears:
“error CMAKE_BOOTSTRAP_SOURCE_DIR …” for CmsystemTools.cxx.

Even the whole building process looks normal, when you type ‘visit’ in your installed VisIt2.13.2 dir/bin, maybe such blunder appears:
"this hardware platform is not supported by visit"
What hell can I do? 
me too.

**Comment by zingale** [comment]
hi, we can't really debug issues with VisIt, so you might want to contact those developers directly.  But in the past, we've had good luck just using the precompiled binaries they provide.  These days though, most of us use yt for visualization of Castro results: http://yt-project.org/
