### ISSUE TITLE
Improve species and aux data for Castro/Thornado

### ISSUE THREAD

**Issue by dwillcox** [AMReX-Astro/Castro#429]
Regarding the ecp/two-moment branch...

For Thornado, we only need to track the electron number density N_e.

Right now N_e is an auxiliary variable and for EOS calls we're getting it from y_e, which we say is the first species. This is a workaround for the fact that we do not load auxiliary variables into `eos_t % aux` before EOS calls in Castro, so it is related to #144 .

To fix this, we should:

1) Enable nspec=0
2) Take out y_e, just put N_e (electron number density) in aux
3) load aux into eos_state before EOS calls
4) in the EOS or `eos_override`, convert N_e to y_e

We can also consider tracking y_e in Castro and converting to/from N_e when calling Thornado.

**Comment by zingale** [comment]
is this still needed @dwillcox

**Comment by zingale** [comment]
the main thing needed is to make sure `eos_state % aux(:)` is filled before every EOS call.

maybe also make a `USE_YE` flag that adds Y_e to the state

**Comment by zingale** [comment]
we now consistently pass aux to all the EOS calls and use this with NSE, so I think this is now a Microphysics issue to do with as they need.
