### ISSUE TITLE
Description of variables in output files needed

### ISSUE THREAD

**Issue by harpolea** [AMReX-Astro/Castro#445]
There should be a table in the docs of what the different output variables are (e.g. I can't find anywhere in the current docs where it defines what `rot_x` means), perhaps with links to where they are defined in the code.

**Comment by zingale** [comment]
this is now done in the `sphinx` branch.

**Comment by zingale** [comment]
http://bender.astro.sunysb.edu/random/Castro/docs/visualization.html#plotfile-variables

**Comment by zingale** [comment]
this was merged
