### ISSUE TITLE
angular_momentum_x et al. in plotfile should respect center

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#447]
We compute the plotfile quantity `angular_momentum_x` in the plotfile by doing 
```
    do k = lo(3), hi(3)
       loc(3) = xlo(3) + (dble(k - lo(3)) + HALF) * dx(3)
       do j = lo(2), hi(2)
          loc(2) = xlo(2) + (dble(j - lo(2)) + HALF) * dx(2)
          do i = lo(1), hi(1)
             loc(1) = xlo(1) + (dble(i - lo(1)) + HALF) * dx(1)

             rho = u(i,j,k,1)
             mom = u(i,j,k,2:4)
             ang_mom = cross_product(loc, mom)

             L(i,j,k,1) = ang_mom(1)

          enddo
       enddo
    enddo
```

but we should really subtract `center(:)` off of `loc` first.  This isn't an issue for problems with the rotation axis at the origin.  Also, using `xlo(:)` to derive the coordinates may not be tile safe (since `lo()`, may be different than `xlo`.

**Comment by maxpkatz** [comment]
Fixed.

>  Also, using xlo(:) to derive the coordinates may not be tile safe

When we use this form, xlo is calculated with respect to the box the MFIter is using, which will be consistent with the tilebox if we are tiling.
