### ISSUE TITLE
add support for non-square cells

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#453]
Atleast for pure hydro problems, it would be useful to support rectangular cells.  In particular, for the XRB problems.  This should mostly be a case of making sure the correct dx is used throughout the code and testing.

**Comment by harpolea** [comment]
As far as I can tell, the only parts of the code which assume square cells are some of the gravity routines. I'm currently running some of the pure hydro tests with rectangular cells and there are no obvious errors so far. I'll keep testing and see if I can find any bugs

**Comment by zingale** [comment]
awesome!

**Comment by zingale** [comment]
the fourth-order stuff assumes equal dx's .  The Laplacian' sneed to be updated

**Comment by zingale** [comment]
some testing was done with #2256 and there is experiment support for this
