### ISSUE TITLE
Interpolater for grad phi in Gravity

### ISSUE THREAD

**Issue by WeiqunZhang** [AMReX-Astro/Castro#469]
I think there is a bug in the interpolation of grad phi in Castro.cpp and Gravity.cpp.  It uses `node_bilinear_interp`, but grad phi is not all nodal.  AMReX currently doesn't have interpolaters for face data.   I will work on that next month because FLASH asks for it.

**Comment by zingale** [comment]
@weiqun, was this implemented in AMReX yet?

**Comment by zingale** [comment]
@WeiqunZhang ping?
