### ISSUE TITLE
extend _cpp_parameters to allow arrays

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#474]
We need to allow arrays in `_cpp_parameters`.  For instance, `castro.center` is not maintained in that file, so it is not automatically documented etc.

**Comment by zingale** [comment]
`center` seems to be an odd parameter.  It is not a static variable in the Castro class.  Rather it is just read in and passed via `ca_set_problem_params` into Fortran.

**Comment by maxpkatz** [comment]
A problem with `center` is that it is often set depending on the geometry, see e.g. sub_chandra.

**Comment by zingale** [comment]
I don't think we need this functionality.
