### ISSUE TITLE
1D Gravity w/ Refinement

### ISSUE THREAD

**Issue by aepolin** [AMReX-Astro/Castro#49]
Multilevel refinement breaks HSE in 1D models. This became a noticeable issue after the 16.08 release.

**Comment by aepolin** [comment]
Running these input&probin files with this ridiculously high resolution model in the hydrostatic_adjust test problem causes fluctuations in the central density fluctuations for multilevel  tagging. 

[HSE_issues.zip](https://github.com/BoxLib-Codes/Castro/files/499383/HSE_issues.zip)

**Comment by zingale** [comment]
valgrind doesn't turn up any issues with these inputs

**Comment by zingale** [comment]
do we know if this is still an issue?  without a test problem, we can really debug this
