### ISSUE TITLE
CUDA MOL solver may not be handling non-Cartesian properly

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#490]
Because we apply the scaled fluxes in the conservative update in `ca_construct_hydro_update_cuda`, we need to make sure that we are incorporating the pressure properly in the momentum flux for non-Cartesian coords.  I don't think we have this term in there.

**Comment by maxpkatz** [comment]
Note: I do not plan to do much with the current CUDA MOL driver going forward. Rather what we will do is make the existing full MOL solver CUDA-aware.

**Comment by zingale** [comment]
closing this, since this is actually part of #477
