### ISSUE TITLE
restart failures with 1D gravity

### ISSUE THREAD

**Issue by aepolin** [AMReX-Astro/Castro#51]
restart returns this error:

PUT_RADIAL_GRAV: INDEX TOO BIG        61440  >        61439
AT i        61440
R / DR IS    10000081380.208332        162760.41666666666
BoxLib::Error::23::FORTRAN:Error:: Gravity_1d.f90 :: ca_put_radial_grav !!!

The same error is reproduced no matter which checkpoint is used for restart, and when the same time step runs without issue in a continuous run.

**Comment by maxpkatz** [comment]
I believe this is fixed in commit 7a245678c7a6bc73e81f6408d82408b1244a90d2. However I would like @aepolin to verify that the gravitational field actually makes sense after a restart before closing.

**Comment by zingale** [comment]
any update on this @aepolin?  Can we close this issue?

**Comment by zingale** [comment]
closing -- we can reopen if we get a new test that shows this still exists.
