### ISSUE TITLE
restore radiation source test problem

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#518]
we seem to have lost the radiation source test problem.  I've found it from CVS and dumped it in the `old_rad_problems` branch.  This needs to be updated to compile.

**Comment by harpolea** [comment]
In `verification.txt`, it says that the output can be analyzed using `fradsource` from `fParallel/data_processing/`. I can't find anything that looks like this in present-day Castro - @zingale would you be able to dig it up from the old CVS?

**Comment by harpolea** [comment]
This is done in  #515
