### ISSUE TITLE
Construct coding style guide

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#524]
Castro should have a style guide for coding consistency in the documentation. We do not need to be especially rigorous here or go all out and apply Google's C++ style guide, but some basic consistency would help in code readability. Some things to include are below, including what I would recommend as the defaults. If there is no objection to implementing such a style guide in general, I will implement it. I will include all items in my list which are not objected to, and we can have a conversation on the remaining ones. Additions are welcome.

- Indentation
Indentation should be spaces, not tabs. 4 spaces preferred.

- Conditionals
Conditionals should appear as
```
if (condition)
{
    ...
}
else if (condition)
{
    ...
}
else
{
    ...
}
```

- Fortran interfaces
All C to Fortran interfaces should use the ISO C binding. The Fortran subroutine should use bind(C, name='subroutine_name'). Data passed by reference from C++ should use `*`, not `&`. Scalars should be passed by value, using the Fortran `value` attribute. For subroutines that are called from C++, it is preferred to prefix the subroutine name with `ca_`.

**Comment by harpolea** [comment]
Can it include something on comments e.g. to ensure that they comply with doxygen?

**Comment by maxpkatz** [comment]
Yes. Is there a tl;dr for what that means?

**Comment by harpolea** [comment]
The doxygen comment blocks documentation is here: http://www.doxygen.nl/manual/docblocks.html#specialblock. I followed the conventions that:
- C++ functions should be documented in the header file using the style 
``` C++
///
/// Description of the function 
///
/// @param a_variable       Brief description of the variable
///
void foo(int bar) { ...
```
Member variables can either be documented using the above style of comment block or with a brief inline description:
``` C++
int var; ///< Brief description after the variable
```
- Fortran functions should be documented by placing a comment block before their definition using the style 
``` fortran
!> @brief Description of the function
!!
!! @param a_variable      Brief description of the variable
subroutine foo(bar)
...
```
Documentation for modules should be similarly formatted, with the comment block again coming *before* the module definition

**Comment by zingale** [comment]
This is all good with me.  I think we have the start of something in the docs, so we should add this to it.

**Comment by zingale** [comment]
https://amrex-astro.github.io/Castro/docs/coding_conventions.html

**Comment by zingale** [comment]
also note #74

**Comment by zingale** [comment]
closing this now, as it's all in the docs now.  For future proposed additions to the coding style, submit a PR to `coding_conventions.rst`
