### ISSUE TITLE
Radiation should throw a runtime error if using single-group solver but NGROUPS > 1

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#528]
RadSuOlson accidentally was being given NGROUPS = 2 at compile time in the test suite, resulting in corrupted plotfiles.

**Comment by harpolea** [comment]
There already seems to be a check for that here https://github.com/AMReX-Astro/Castro/blob/3aebeb1157c95625aad23b6db374112df92f1fc6/Source/radiation/Radiation.cpp#L259-L261

I wonder why it wasn't throwing an error?

**Comment by maxpkatz** [comment]
That check only ensures that, if the inputs file sets ngroups, that it's equal to what you compiled with. It's just a sanity check since you're not supposed to be setting that at runtime in the inputs file now. And indeed, RadSuOlson doesn't do that.

**Comment by harpolea** [comment]
oh so you need a check for the SolverType rather than checking that the compiled and inputs file ngroups are equal?

**Comment by maxpkatz** [comment]
Yes, that's what this issue was suggesting, IIRC.

**Comment by maxpkatz** [comment]
I was specifically looking at the code starting here:

https://github.com/AMReX-Astro/Castro/blob/3aebeb1157c95625aad23b6db374112df92f1fc6/Source/driver/Castro_setup.cpp#L606

Should be able to throw a fail in if `Radiation::nGroups > 1` but `!Radiation::do_multigroup`.

**Comment by harpolea** [comment]
Is there a reason not to throw the error here as soon as the SolverType is read in? https://github.com/AMReX-Astro/Castro/blob/3aebeb1157c95625aad23b6db374112df92f1fc6/Source/radiation/Radiation.cpp#L118-L133

**Comment by maxpkatz** [comment]
I think it works to put it there. Specifically I would put it just below the next block of code that defines `do_multigroup` (based on what the `SolverType` is).

**Comment by harpolea** [comment]
fixed by #540
