### ISSUE TITLE
S_old should not be changed in expand_state

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#536]
For CTU (and others), S_old is directly updated in the call to expand_state, when we do clean_state. I don't like this: S_old should be strictly static during an update. It is done with good intentions, since FillPatch is sourced from StateData, and as written we have to call clean_state on S_old so that we can get "clean" data in Sborder. I think the way to fix this -- and simultaneously my observation in issue #324 -- is to do the FillPatch first and only then call clean_state, on Sborder directly.

**Comment by zingale** [comment]
Note that the proposed fix here is opposite the approach we took with #721 , where we relied on S_old being clean so we could eliminate the `clean_state` in `initialize_do_advance`

**Comment by maxpkatz** [comment]
I'm not sure what I was thinking when I filed this bug, because indeed we already do call clean_state on S_old in the beginning of the step because some of the data may have been fillpatched into creation just prior to the advance. And it's important that this data be valid.
