### ISSUE TITLE
SDC incompatible with VODE90

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#547]
sdc_util.f90 assumes some functions specific to the VODE integrator (dvode, dgesl, dgefa) so it won't link if VODE90 is used as the integrator:

```
/usr/bin/ld: tmp_build_dir/o/2d.gnu.MPI.EXE/sdc_util.o: in function `__sdc_util_MOD_sdc_solve':
/home/mkatz/codes/Castro/Exec/science/flame_wave/../../../Source/driver/sdc_util.F90:248: undefined reference to `dvode_'
/usr/bin/ld: /home/mkatz/codes/Castro/Exec/science/flame_wave/../../../Source/driver/sdc_util.F90:202: undefined reference to `dgesl_'
/usr/bin/ld: /home/mkatz/codes/Castro/Exec/science/flame_wave/../../../Source/driver/sdc_util.F90:196: undefined reference to `dgefa_'
```

**Comment by zingale** [comment]
This will eventually need to be cleaned up, but in the short term, we could either make it work with vode90 also, or fix the linking problem when someone compiles with vode90.

**Comment by maxpkatz** [comment]
I've solved this in the short term by ifdef'ing out SDC if we're building with CUDA.

**Comment by maxpkatz** [comment]
Assigning this to @dwillcox. The planned solution here is to compile VODE and VODE90 simultaneously, which would automatically include the missing linpack routines.

**Comment by maxpkatz** [comment]
I've also worked around this on the CPU side for now by only defining in the relevant LINPACK bits packaged with VODE if INTEGRATOR==0.

**Comment by zingale** [comment]
This is actually tricky for (atleast) two reasons:

1. VODE90 hardcodes in the name of the RHS and Jacobian routine, but for the SDC method,
    we need to do things differently than the Strang burn, so we need a different RHS routine.  

    This means we need to switch back to the old VODE style of passing in the name of the
    RHS routine

2. The SDC method has a different set of rpar than Strang, but in VODE90, the rpar is part of the `dvode_t` type.  This prevents us from switching it out.

    We need to switch back to the old VODE method of passing in rpar separately.
