### ISSUE TITLE
Mechanism to handle 1D spherical problem w/ r != 0

### ISSUE THREAD

**Issue by jaharris87** [AMReX-Astro/Castro#55]

**Comment by maxpkatz** [comment]
For starters, this is intended to only use an outflow BC.

**Comment by jaharris87** [comment]
Here are some routines I know make the assumption of r = 0 for indexing (this is certainly not exhaustive):

Gravity_1d.f90:
ca_compute_radial_mass
ca_put_radial_grav
ca_put_radial_phi

Gravity.cpp:
install_level
make_radial_phi

**Comment by zingale** [comment]
we don't have a use case for this currently.  PRs welcomed.
