### ISSUE TITLE
SDC and MOL don't need the sources to be fillpatched

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#553]
Since the source terms are not used in the predictor for hydro, I don't think we need to do a FillPatch on `sources_for_hydro` in either `Castro_advance_sdc.cpp` or `Castro_advance_mol.cpp`.

**Comment by maxpkatz** [comment]
Agreed. The source terms for MOL/SDC only need to be valid on the valid domain, if the hydro is only generating an update on the valid domain (which is currently true for all hydro methods).

**Comment by maxpkatz** [comment]
(Note that the FillPatch is also important for doing srctoprim.)

**Comment by zingale** [comment]
neither of these methods need srctoprim

**Comment by zingale** [comment]
I think there is a bit of an issue on the fillpatch in `do_old_sources`.  We call `do_advance_mol` with the _stage_ time, and that time is passed into `do_old_sources`, and hence used in the `FillPatch` in there.  But since for later stages that will be a intermediate between the old and new time, it will need to interpolate in time, but there is no valid new time-data.  Instead, what we need here, atleast for a single level, is to ensure the fill is only done using the old time (`old_source`) data.

It would actually be a lot cleaner if we removed the ghost fill from `do_old_sources`, since that only really makes sense for CTU integration.  Things are much more complicated for 4th order MOL/SDC.

**Comment by maxpkatz** [comment]
I'm OK with moving the fillpatch out of do_old_sources and explicitly writing it in the CTU advance.

**Comment by zingale** [comment]
The next step is to get the 4th order sources correctly done in MOL and CTU -- some of the fillpatches seem to use the node time instead of the time corresponding to the MF, so the time-interpolation is probably not working properly.

**Comment by zingale** [comment]
fixed in #574
