### ISSUE TITLE
create disk-periodic BCs

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#602]
We should create (probably via AMReX) disk-based BCs.  The idea is that if you flow out of -x you come in -y (and vice-versa).  We'd have to swap velocity components as well.  This might be able to use the periodic BC logic in AMReX + some extra hook.  

This would allow us to run the 3-d flame_wave problem as a quadrant (saving a lot of computer)

**Comment by zingale** [comment]
we need a test problem for this.  @KiranEiden did you make one?

**Comment by KiranEiden** [comment]
> we need a test problem for this. @KiranEiden did you make one?

I made a test problem during my last week at LBL, but the BC filler was still generating NaNs when I left. The current version is on the [vortex branch of my fork in the simple_vortex directory](https://github.com/KiranEiden/Castro/tree/vortex/Exec/hydro_tests/simple_vortex).

**Comment by zingale** [comment]
we've decided against this route.
