### ISSUE TITLE
Tagging needs a substantial rework

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#606]
Tagging has some limitations that make it inappropriate for GPU acceleration, and in general should be reworked anyway. Specifically:

- We should merge the default tagging functions into one large function rather than have redundant separate functions for density, temperature, etc. This means we can just have one large kernel launch rather than several kernel launches that derive a MultiFab and then load the same state data in. We could have one combined function that works on State_Type, React_Type, Rad_Type, etc., or we could have separate ones for each of these types of StateData. In some cases we will have to deal with derived data; e.g. for t_sound_t_enuc we either need to handle that as a special case or just derive it by hand inside the reactions tagging routine.

- We can and should operate directly on the BaseFab char data of the TagBox, rather than using get_itags/tags_and_untags to get a temporary integer fab (which is not GPU accelerated and would not be trivial to accelerate).

**Comment by maxpkatz** [comment]
One blocker to this is that Rad2TShock uses a custom Castro_error.cpp. I'll need to remove this. Does anyone object to using tagging based on first derivatives instead of second derivatives for this problem? @WeiqunZhang

**Comment by zingale** [comment]
this has been done in #611
