### ISSUE TITLE
cuda-memcheck segfault on cori-gpu

### ISSUE THREAD

**Issue by jmsexton03** [AMReX-Astro/Castro#609]
I was trying to run Sedov on the corigpu system under cuda-memcheck and got a segfault/error. It runs cleanly under nvprof and "normally." 

The specific configuration details are below:

I was using development amrex and development castro
source git hashes:
 Castro              : 19.05-9-gf5d65a0be
 AMReX               : 19.05-72-g30123d14a

for the sedov problem with  `make -j AMREX_HOME=../../../../amrex_dev/ COMP=pgi USE_MPI=FALSE USE_CUDA=TRUE`

with modules:

Currently Loaded Modulefiles:
  1) esslurm            2) cuda/10.0          3) pgi/18.10          4) mvapich2/2.3       5) modules/3.2.10.6

cuda-memcheck causes a segfault immediately after it tries to read probin.3d.sph.testsuite:

`srun -n 1 cuda-memcheck ./Castro3d.pgi.CUDA.ex inputs.3d.sph.testsuite
Initializing CUDA...
CUDA initialized with 1 GPU
AMReX (19.05-72-g30123d14a5b5) initialized

Starting run at 20:54:33 UTC on 2019-05-08.
Successfully read inputs file ... 

Castro git describe: 19.05-9-gf5d65a0be
AMReX git describe: 19.05-72-g30123d14a

reading extern runtime parameters ...
Segfault
========= CUDA-MEMCHECK
========= Error: process didn't terminate successfully
=========        The application may have hit an error when dereferencing Unified Memory from the host. Please rerun the application under cuda-gdb or Nsight Eclipse Edition to catch host side errors.
========= No CUDA-MEMCHECK results found
srun: error: cgpu01: task 0: Exited with exit code 1`

**Comment by dwillcox** [comment]
I can reproduce this issue as listed, compiling not in debug mode and using `cuda-memcheck`.

The segfault does not occur when compiling in debug mode with `DEBUG=TRUE` and running either normally, under `cuda-memcheck`, or under `cuda-gdb` (with or without `set cuda memcheck on`).

The segfault also does not occur when running in non-debug mode normally or under `cuda-gdb`, even if `set cuda memcheck on` is used in `cuda-gdb`.

On this basis, it seems likely the segfault arises from a bug in the standalone `cuda-memcheck` program.
