### ISSUE TITLE
corner ghost cell fill crash in flame_wave due to new fillpatch changes for new grids

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#65]
We recently changed the fillpatch when creating new grids to include ghost cells.  For the `flame_wave` problem, this now results in a crash in the -Y boundaries (HSE).

We integrate downward from the bottom valid zone in along y to initialize the -Y ghost cells using HSE.  In a corner, there is now valid data above us, so we integrate down from the ghost cells in the -X direction.  

With this new change, we are now in a situation where the data we are starting out integration from is all 0, so the integration does not work, and we crash (with an HSE non-convergence).

So it seems that -Y is being filled before -X in the lower left corner.  Why?

Possible fixes are to detect if the state we are starting out integration from is 0, and if so, defer the initialization.  In the ghost cell fill, we should eventually encounter an X for which there is real domain above us, and then we can proceed with the -Y integration.  After we do all of the cells, we can simply copy the first column of valid cells into the corner.

Alternately, we can use the initial model to initialize the corners always, via extrapolation, or use the initial model just to set the starting point of the integration.

**Comment by zingale** [comment]
this seems to be aggravated using the AMReX gpu branch

**Comment by maxpkatz** [comment]
I don't believe this is still a problem. @zingale can you verify?

**Comment by zingale** [comment]
it does appear that this is no longer an issue.  I can remove the changes from that workaround commit and it still works (but I think it is still safest to leave those changes in, in case the ghost cells are filled in a different order).
