### ISSUE TITLE
Find optimal number of CUDA streams

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#672]
AMReX currently hardcodes the number of CUDA streams to 16:

https://github.com/AMReX-Codes/amrex/blob/19.09/Src/Base/AMReX_GpuDevice.H#L144

This seems to cause stream serialization due to a bug in the CUDA driver, as well as known behavior related to the default number of compute channels in CUDA (CUDA_DEVICE_MAX_CONNECTIONS defaults to 8; it can be as large as 32). We should adjust the AMReX `max_gpu_streams` parameter as well as the CUDA environment variable and find the right combination.

**Comment by zingale** [comment]
this seems to be resolved in https://github.com/AMReX-Codes/amrex/pull/585
