### ISSUE TITLE
setVal on device needs to be launched in a kernel

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#680]
The Fab setVal for the shock variable in Castro_ctu_hydro.cpp needs to be launched in a kernel region, otherwise it will happen on the host and cause unintended race conditions. We should fix this.

**Comment by zingale** [comment]
do we also need to do `hydro_source` in the same file?

**Comment by maxpkatz** [comment]
No, MultiFab setVal is fine.

**Comment by zingale** [comment]
this has been fixed
