### ISSUE TITLE
Sponge is not time-centered

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#7]
The sponge is applied by subtracting dt \* (rho \* u)^(n+1) / sponge_timescale from the momentum. This is not time-centered; we should apply it in a predictor-corrector fashion like other source terms. As a consequence of this change, the source terms to the hydrodynamics would also "see" the sponge, making the hydro update more accurate.

**Comment by zingale** [comment]
this is addressed by castro.time_center_sponge﻿⁠⁠⁠⁠

turning this on by default would fix the issue

**Comment by zingale** [comment]
is this issue really able to be closed just by changng this default?  Any reason not too?

**Comment by maxpkatz** [comment]
Yes, this could be closed by changing the default. The only reason not to would be that it changes behavior for users. However since I think the behavior change is good, I suggest that we do it.

**Comment by zingale** [comment]
this has been changed now

**Comment by maxpkatz** [comment]
The energy source term is not done correctly in the sponge if it is time centered. The traditional approach is to use v^n . src^n for the old-time energy source term and v^{n+1} . src^{n+1} for the new-time energy source term (see also #57). The current version always updates the momentum first before evaluating the energy source term, which we usually only do for the new-time source (see, e.g., ca_gsrc). This is a holdover from the version of the sponge that was not initially time-centered.

I plan to fix this and #57 by re-implementing the sponge using the standard time centered formalism, and drop the capability to use the old non-time-centered approach, as I assume there is no one will who object to this.

**Comment by zingale** [comment]
no objection
