### ISSUE TITLE
restart tests fail when run on GPUs

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#706]
The DustCollapse restart test problem fails when run in the testsuite using PGI+CUDA:

http://groot.astro.sunysb.edu/Castro/test-suite/gpu/2019-12-03-004/dustcollapse-restart.html

The errors are small, but non-zero.  @guadabsb15 saw this behavior on summit.  It may only affect problems with gravity?

**Comment by maxpkatz** [comment]
I don't think this has anything to do with the restart test. The CUDA version of the multipole BC solver is non-deterministic. You can get a non-zero diff on DustCollapse if you just run the same problem twice with max_step = 0 and compare the plotfiles. It is the same issue as #679. It's not a code bug, it's just a feature of the GPU and our implementation on it -- when you have thousands of threads all executing an atomic add, it's not necessarily going to be deterministic.
