### ISSUE TITLE
Erroneous arithmetic operation on gpu for wdmerger

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#715]
Build wdmerger on summit with `USE_CUDA=TRUE COMP=pgi DEBUG=TRUE`

NOTE: remove `.txt` on the files below -- needed that for github to be happy

Then run with this script:

[summit_gpu.submit.txt](https://github.com/AMReX-Astro/Castro/files/3993038/summit_gpu.submit.txt)

with these inputs / probin

[inputs_test_wdmerger_3D.txt](https://github.com/AMReX-Astro/Castro/files/3993039/inputs_test_wdmerger_3D.txt)
[probin_test_wdmerger_3D.txt](https://github.com/AMReX-Astro/Castro/files/3993040/probin_test_wdmerger_3D.txt)

It doesn't make it more than 1 step and gives:
```

  Contributions to the state from the new-time sources:
       mass added: 0
       xmom added: -6.378185691e+29
       ymom added: 2.933243345e+31
       zmom added: -2.893375843e+24
       eint added: 0
       ener added: -2.987827719e+44

Castro::do_new_sources() time = 0.106157363

  Subcycle completed

  Subcycling complete

  Zones advanced per microsecond at this level: 5.770520159

[Level 0 step 1] Advanced 16777216 cells
[Level 1 step 1] ADVANCE with dt = 0.00172266757
Erroneous arithmetic operation
Erroneous arithmetic operation
Erroneous arithmetic operation
```

**Comment by maxpkatz** [comment]
I don't think this is the right inputs file because it only has one level, but you have at least two levels in the above output.

**Comment by maxpkatz** [comment]
This should be resolved, I fixed a race condition that was present when fab.init_snan = 1 (which is true in DEBUG mode).
