### ISSUE TITLE
Remove neutrino radiation capabilities

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#718]
Neutrino radiation is untested and, as far as we know, unused for the last several years. I propose removing it. We are integrating Thornado for neutrino modelling, and while it may or may not be a one-for-one replacement, it will still allow us to do the science with neutrinos we want to do.

I would like signoff from the following people:

@zingale 
@WeiqunZhang 
@dwillcox 

Commentary from anyone else (e.g. @jaharris87) is appreciated.

**Comment by maxpkatz** [comment]
I have removed neutrino build support from the makefile and will be removing code from the source files in pieces this month. Neutrino diffusion will be officially unsupported for the 20.02 release.

This is not a commitment to never do neutrino diffusion again. However, if we do it in the future it needs to be done in a way where we can generalize the radiation solver to also do neutrinos with a minimal amount of unique code, and we absolutely need multiple test cases and relevant supporting files like opacity tables.

**Comment by zingale** [comment]
I think that the thornado coupling that is in a branch is the preferred way of doing neutrinos now
