### ISSUE TITLE
is radiation pressure gradient stored in the flux registers?

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#82]
The hydrodynamical fluxes don't include the radiation pressure term and for some geometries, don't include the hydrodynamic pressure either.

Look, for instance, in the 1-d `consup` routine -- we add `dt * area(i) * q1(i,GDPRES)` to the `UMX` flux that will go into the flux register for the hyperbolic correction later, when we are Cartesian.

But shouldn't there also be the radiation pressure contribution here as well (for the radiation routine)? 

For non-Cartesian geometries, we probably need to add it to the pressure flux register.

**Comment by zingale** [comment]
@WeiqunZhang do you agree that the radiation pressure should be put into a flux register?

**Comment by zingale** [comment]
the actual line is in `Castro_2d.F90`, where we do:

```
  if (coord_type .eq. 1) then                                                                      
     pradial(lo(1):hi(1)+1,lo(2):hi(2)) = q1(lo(1):hi(1)+1,lo(2):hi(2),GDPRES) * dt                
  end if                                                                                           
```

**Comment by zingale** [comment]
okay, so maybe I am confused then.

Looking at `riemann_2d.F90`, it does appear that `GDPRES` is the total pressure

But looking at `consup`, we add the pressure gradient of `GDPRES` to the momentum update and then explicitly construct the radiation contribution and add that.  Then we difference the kinetic energy between the 2 to get the KE addition from radiation.

So there, it seems like we are expecting that `GDPRES` does not include the radiation term.

Unless I am just plain confused...

**Comment by WeiqunZhang** [comment]
It seems that radiation pressure is added twice.  I think we should do a radiation Sod problem with radiation pressure completely dominates.  Then the solution should be just the pure hydro Sod with gamma = 4/3.  I think the second Castro paper has a test problem like that.

**Comment by zingale** [comment]
okay.  I'll try that tomorrow.  

I don't think I changed any of the logic recently, but it may be that we changed the meaning of GDPRES at some point in the past without understanding the implications.

**Comment by zingale** [comment]
current status:

`GDPRES` does not include radiation, so it needs to be explicitly added to the pressure flux register

We should test things out on the radiation-dominated Sod problem Weiqun suggests.

**Comment by zingale** [comment]
okay... the term in question in the momentum equation is 

lambda grad{E_r}

so this is not something that is a simple gradient or divergence (because of the lambda).  This means that it cannot fit into our basic flux correction scheme.

It is not clear that we can just pass on doing anything though -- it may be that we still need to correct this term at C-F interfaces, but that would require additional machinery.

**Comment by zingale** [comment]
I think that this is settled now, because of the form of the term.
