### ISSUE TITLE
backtraces less helpful with AMREX_PARALLEL_FOR_3D

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#825]
When we parallelize with AMREX_PARALLEL_FOR_3D, a backtrace points to the top of the loop, not the line in the lambda that was the cause of the problem.

We should fix this so that in debug mode we can get a useful backtrace.

**Comment by zingale** [comment]
it looks like we want to use `amrex::ParallelFor` instead:

```
for ( MFIter mfi(my_data,TilingIfNotGPU()); mfi.isValid(); ++mfi ) {
    const Box& bx = mfi.tilebox();
    const Array4<Real> & data = my_data.array(mfi);
    amrex::ParallelFor(bx, ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
    {
        data(i,j,k,n) = ...
    });
}```

**Comment by maxpkatz** [comment]
I'll note that with #842 I started doing this and we should continue to expand this practice for new C++ code we write.

**Comment by maxpkatz** [comment]
Note: for amrex::ParallelFor(), in places where we would have used `cycle` in Fortran, the correct C++ replacement is `return`, not `continue`, because the code is actually a lambda function. The code will fail to compile with `continue` so this will be easy to catch.

**Comment by zingale** [comment]
most of these have been dealt with now.
