### ISSUE TITLE
Use new DeriveFuncFab interface

### ISSUE THREAD

**Issue by maxpkatz** [AMReX-Astro/Castro#841]
Right now in Castro for the "derive" routines (that calculate some derived quantity based on StateData, like kinetic energy from momentum and density) we use the old Fortran-style interface in AMReX_Derive.H (DeriveFunc3D). These need to be updated to the new DeriveFuncFab interface which has more useful data structures passed to it, and then switched to AMReX parallel for launches in C++. There's examples in amrex/Tutorials/GPU/CNS/CNS_derive.cpp (and CNS_setup.cpp) to template on. The most important ones to target first are derkingeng and derangmomx/y/z since these are always used in sum_integrated_quantities.

**Comment by zingale** [comment]
I think this is pretty much done now, aside from the diffusion ones which are blocked by #813
