### ISSUE TITLE
move Exec/science into its own repo

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#859]
Should we create a separate `Castro_science` repo that lives in AMReX-Astro?  The justification is that if we move `Exec/science/` into its own repo, then we can enforce a PR-workflow in Castro more easily, since the majority of the time we push directly to development without doing a PR is for our own science problems.

Note: our science will still be completely open, just in a separate repo with more-relaxed push rules.

Please comment or give a thumbs-up or thumbs-down @harpolea @dwillcox @maxpkatz @KiranEiden @guadabsb15 and anyone who I missed "@"-ing.

**Comment by zingale** [comment]
We seem to be onboard on this.  I would propose waiting until after the 20.05 release and then splitting it off then.

**Comment by maxpkatz** [comment]
Note: we'd like to do this in a way that preserves the git history of these problems.

**Comment by zingale** [comment]
https://medium.com/@ayushya/move-directory-from-one-repository-to-another-preserving-git-history-d210fa049d4b

**Comment by zingale** [comment]
I think we've grown comfortable with the new PR workflow
