### ISSUE TITLE
thermal, species, and enthalpy conductivity all use the same microphysics routine

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#86]
At the moment, the thermal, species, and enthalpy conductivities all call the routine `thermal_conductivity` to get the transport coefficients.  This means that we cannot use all of these pieces of physics together (unless the transport coefficients all have the same numerical value).

We should separate these into separate interfaces.

**Comment by zingale** [comment]
actually, the enthalpy part is derived from the thermal by dividing through by cp, so that appears correct.

**Comment by zingale** [comment]
also, species diffusion is only 1-d only -- do we really need this?

**Comment by zingale** [comment]
@asalmgren : is species diffusion being used by anyone in Castro?  or has this role been taken over by other codes (e.g. Maui)?

**Comment by maxpkatz** [comment]
Since we've removed code to diffuse quantities other than temperature, this issue is now irrelevant.
