### ISSUE TITLE
does MHD really need to store cs[AMREX_SPACEDIM]

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#952]
We seem to compute the sound speeds and store them in `cs[AMREX_SPACEDIM]` solely for the purpose of `check_for_mhd_cfl_violation()`.  We can save a lot of memory by computing them on the fly instead.  Are there any other anticipated uses of these?

**Comment by guadabsb15** [comment]
I agree, we should compute them on the fly

**Comment by guadabsb15** [comment]
maybe the motivation was to reuse them for the eigenvectors? but I think it would be better just to compute them on the cfl_violation routine

**Comment by zingale** [comment]
this is addressed in #964
