### ISSUE TITLE
is EOS call in MHD HLLD needed?

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Castro#955]
In HLLD, we come in with qleft/qright, and then we convert to convert to conservative variables and compute the fluxes from the primitive state.

For the primitive state, we call `eos(eos_input_rp, ...)` but in every case I am aware of, we already have a valid `QREINT` in the primitive input state (either from the reconstruction or in the ct_update where we did a constoprim call before the Riemann.

So I think these EOS calls can be removed.

It is also the case that in a lot of places we already have the conservative state that we could send in as input, potentially eliminating the need to do the PtoC calls here (although we'd still need to compute the pressure for the flux)

**Comment by guadabsb15** [comment]
we can definitely remove the EOS call from `PtoC`, but I think the other two we might still need them for `gam1`?  But we could probably get that, on the plm (when we get `q(i,j,k,QREINT)`) and on the ctu routines that convert from conservative to primitive

**Comment by guadabsb15** [comment]
If we were to remove PtoC, and send the conservative states, would we compute the pressure using an EOS in hlld? If that is the case, by doing that could we lose some information from the reconstructed pressure coming from the plm?

**Comment by zingale** [comment]
indeed, so perhaps we need to think more carefully about this.

**Comment by zingale** [comment]
some of this cleaning was done in #969
